# Generated by Django 3.1 on 2022-02-01 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsetbelonging',
            name='buid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='qsetbelong_buid', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='clientid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='qsetbelong_clientid', to='onboarding.bt', verbose_name='Client'),
        ),
    ]
