# Generated by Django 3.2 on 2022-03-30 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peoples', '0001_initial'),
        ('onboarding', '0001_initial'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignedtogroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_grps', to='peoples.pgroup'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assignedtopeople',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.event'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='performedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_performedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='qsetbelong_bu', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='qsetbelong_client', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='questionsetbelonging_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='questionsetbelonging_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='qset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.questionset', verbose_name='Question Set'),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.asset'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='qset_bus', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='qset_clients', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='questionset_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionset',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='questionset_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.questionset', verbose_name='Belongs To'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='category_types', to='onboarding.typeassist', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='question',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='question',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='question_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='question_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='question',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='unit_types', to='onboarding.typeassist', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='jobneeddetails',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneeddetails_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobneeddetails',
            name='jobneed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.jobneed', verbose_name='Jobneed'),
        ),
        migrations.AddField(
            model_name='jobneeddetails',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneeddetails_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobneeddetails',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='jobneeddetails',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneed_assets', to='activity.asset', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneedf_bus', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneed_clients', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneed_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobs', to='activity.job', verbose_name='Job'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneed_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.jobneed', verbose_name='Belongs to'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='People'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneed_performedby', to=settings.AUTH_USER_MODEL, verbose_name='Performed by'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='pgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='peoples.pgroup', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='qset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.questionset', verbose_name='QuestionSet'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='ticket_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.typeassist', verbose_name='Ticket Category'),
        ),
        migrations.AddField(
            model_name='job',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.asset', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='job',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_bus', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='job',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_clients', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='job',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='geofence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.geofencemaster', verbose_name='Geofence'),
        ),
        migrations.AddField(
            model_name='job',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.job', verbose_name='Belongs to'),
        ),
        migrations.AddField(
            model_name='job',
            name='people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_aaatops', to=settings.AUTH_USER_MODEL, verbose_name='Aggresive auto-assign to People'),
        ),
        migrations.AddField(
            model_name='job',
            name='pgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='peoples.pgroup', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='job',
            name='qset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.questionset', verbose_name='QuestionSet'),
        ),
        migrations.AddField(
            model_name='job',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_shifts', to='onboarding.shift', verbose_name='Shift'),
        ),
        migrations.AddField(
            model_name='job',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='job',
            name='ticket_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_tktcategories', to='onboarding.typeassist', verbose_name='Ticket Category'),
        ),
        migrations.AddField(
            model_name='event',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='event',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='event_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='event_device', to='activity.device'),
        ),
        migrations.AddField(
            model_name='event',
            name='eventtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='event_types', to='onboarding.typeassist'),
        ),
        migrations.AddField(
            model_name='event',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='event_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='escalationmatrix',
            name='assignedgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='escalation_grps', to='peoples.pgroup'),
        ),
        migrations.AddField(
            model_name='escalationmatrix',
            name='assignedperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='escalation_people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalationmatrix',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='escalationmatrix',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='escalationmatrix_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalationmatrix',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='escalationmatrix_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalationmatrix',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='device',
            name='belongsTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.device'),
        ),
        migrations.AddField(
            model_name='device',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='device',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='device_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='devicetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='device_types', to='onboarding.typeassist'),
        ),
        migrations.AddField(
            model_name='device',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='device_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='runningStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='device_status', to='onboarding.typeassist'),
        ),
        migrations.AddField(
            model_name='device',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='attachment_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='attachment_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='ownername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.typeassist'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='asset',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_brands', to='onboarding.typeassist', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='asset',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_bus', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_categories', to='onboarding.typeassist', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='asset',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_clients', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='asset',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.asset', verbose_name='Belongs to'),
        ),
        migrations.AddField(
            model_name='asset',
            name='serv_prov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_serv_providers', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='asset',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_subcategories', to='onboarding.typeassist', verbose_name='Sub Category'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_types', to='onboarding.typeassist', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='asset',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_units', to='onboarding.typeassist', verbose_name='Unit'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('bu', 'ticketno'), name='bu_ticketno_uk'),
        ),
        migrations.AddConstraint(
            model_name='questionsetbelonging',
            constraint=models.UniqueConstraint(fields=('qset', 'question', 'client', 'bu'), name='qset_question_client_bu_uk'),
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.UniqueConstraint(fields=('qset_name', 'parent', 'type', 'client', 'bu'), name='name_type_parent_type_client_bu_uk'),
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.CheckConstraint(check=models.Q(slno__gte=0), name='slno_gte_0_ck'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('ques_name', 'answertype', 'client'), name='ques_name_type_client_uk'),
        ),
        migrations.AddConstraint(
            model_name='jobneed',
            constraint=models.CheckConstraint(check=models.Q(gracetime__gte=0), name='jobneed_gracetime_gte_0_ck'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('jobname', 'asset', 'qset', 'parent', 'identifier'), name='jobname_asset_qset_id_parent_identifier_uk'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(check=models.Q(gracetime__gte=0), name='gracetime_gte_0_ck'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(check=models.Q(planduration__gte=0), name='planduration_gte_0_ck'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(check=models.Q(expirytime__gte=0), name='expirytime_gte_0_ck'),
        ),
    ]
