# Generated by Django 3.2.14 on 2022-07-29 07:37

import apps.peoples.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0002_initial'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='mdtz')),
                ('ctzoffset', models.IntegerField(default=-1, verbose_name='TimeZone')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, unique=True)),
                ('seqno', models.IntegerField(null=True)),
                ('wpstatus', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=30, verbose_name='Status')),
                ('workstatus', models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('COMPLETED', 'Completed')], max_length=30, verbose_name='Work Status')),
                ('attcount', models.IntegerField(null=True, verbose_name='Attachment Count')),
                ('approvedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='wp_approvers', to=settings.AUTH_USER_MODEL, verbose_name='')),
                ('bu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='wp_sites', to='onboarding.bt', verbose_name='Bt')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='wp_clients', to='onboarding.bt', verbose_name='Client')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='workpermit_cusers', to=settings.AUTH_USER_MODEL)),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='workpermit_musers', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.workpermit', verbose_name='')),
                ('wptype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.questionset', verbose_name='WorkPermit Type')),
            ],
            options={
                'db_table': 'workpermit',
                'ordering': ['mdtz'],
                'get_latest_by': ['mdtz', 'cdtz'],
                'abstract': False,
            },
        ),
    ]
