# Generated by Django 3.2 on 2022-05-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='slno',
            new_name='seqno',
        ),
    ]
