# Generated by Django 3.2.18 on 2023-06-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='iscritical',
            field=models.BooleanField(default=False, verbose_name='Critical'),
        ),
    ]
