# Generated by Django 3.2.14 on 2022-08-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_workpermit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='attcount',
        ),
        migrations.AddField(
            model_name='ticket',
            name='attachmentcount',
            field=models.IntegerField(default=0, verbose_name='Attachment Count'),
        ),
    ]
