# Generated by Django 3.2 on 2022-03-30 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobneeddetails',
            table='jobneeddetails',
        ),
    ]
