# Generated by Django 3.2 on 2022-05-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_rename_slno_job_seqno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='owner',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
