# Generated by Django 3.1 on 2022-02-01 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0001_initial'),
        ('tenants', '0001_initial'),
        ('onboarding', '0002_auto_20220201_1540'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0002_auto_20220201_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_brands', to='onboarding.typeassist', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='asset',
            name='buid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_buids', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_categories', to='onboarding.typeassist', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='asset',
            name='clientid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_clientids', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='asset',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.asset', verbose_name='Belongs to'),
        ),
        migrations.AddField(
            model_name='asset',
            name='serv_prov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_serv_providers', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='asset',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_subcategories', to='onboarding.typeassist', verbose_name='Sub Category'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_types', to='onboarding.typeassist', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='asset',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_units', to='onboarding.typeassist', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='job',
            name='assetid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.asset', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='job',
            name='buid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_buids', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='job',
            name='clientid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_clientids', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='job',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='gfid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.geofencemaster', verbose_name='Geofence'),
        ),
        migrations.AddField(
            model_name='job',
            name='groupid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='peoples.pgroup', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='job',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.job', verbose_name='Belongs to'),
        ),
        migrations.AddField(
            model_name='job',
            name='peopleid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_aaatops', to=settings.AUTH_USER_MODEL, verbose_name='Aggresive auto-assign to People'),
        ),
        migrations.AddField(
            model_name='job',
            name='qsetid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.questionset', verbose_name='QuestionSet'),
        ),
        migrations.AddField(
            model_name='job',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_shifts', to='onboarding.shift', verbose_name='Shift'),
        ),
        migrations.AddField(
            model_name='job',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='job',
            name='ticket_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_tktcategories', to='onboarding.typeassist', verbose_name='Ticket Category'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='assetid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneed_assets', to='activity.asset', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='buid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneedf_buids', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='clientid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneed_clientids', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneed_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='groupid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='peoples.pgroup', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='jobid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobs', to='activity.job', verbose_name='Job'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneed_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.jobneed', verbose_name='Belongs to'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='peopleid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='People'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneed_performedby', to=settings.AUTH_USER_MODEL, verbose_name='Performed by'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='qsetid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.questionset', verbose_name='QuestionSet'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='ticket_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.typeassist', verbose_name='Ticket Category'),
        ),
        migrations.AddField(
            model_name='jobneeddetails',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneeddetails_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobneeddetails',
            name='jobneedid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.jobneed', verbose_name='Jobneed'),
        ),
        migrations.AddField(
            model_name='jobneeddetails',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneeddetails_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobneeddetails',
            name='quesid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='jobneeddetails',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='category_types', to='onboarding.typeassist', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='question',
            name='clientid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='question',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='question_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='question_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='question',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='unit_types', to='onboarding.typeassist', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='assetid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.asset'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='buid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='qset_buids', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='clientid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='qset_clientids', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='questionset_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionset',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='questionset_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.questionset', verbose_name='Belongs To'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='questionsetbelonging_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='questionsetbelonging_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='qsetid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.questionset', verbose_name='Question Set'),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='quesid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('jobname', 'assetid', 'qsetid', 'parent', 'identifier'), name='jobname_assetid_qset_id_parent_identifier_uk'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(check=models.Q(gracetime__gte=0), name='gracetime_gte_0_ck'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(check=models.Q(planduration__gte=0), name='planduration_gte_0_ck'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(check=models.Q(expirytime__gte=0), name='expirytime_gte_0_ck'),
        ),
        migrations.AddConstraint(
            model_name='jobneed',
            constraint=models.CheckConstraint(check=models.Q(gracetime__gte=0), name='jobneed_gracetime_gte_0_ck'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('ques_name', 'answertype', 'clientid'), name='ques_name_type_clientid_uk'),
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.UniqueConstraint(fields=('qset_name', 'parent', 'type', 'clientid', 'buid'), name='name_type_parent_type_clientid_buid_uk'),
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.CheckConstraint(check=models.Q(slno__gte=0), name='slno_gte_0_ck'),
        ),
        migrations.AddConstraint(
            model_name='questionsetbelonging',
            constraint=models.UniqueConstraint(fields=('qsetid', 'quesid', 'clientid', 'buid'), name='qsetid_quesid_clientid_buid_uk'),
        ),
    ]
