# Generated by Django 3.2 on 2022-04-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='tzoffset',
            new_name='ctzoffset',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='tzoffset',
            new_name='ctzoffset',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='tzoffset',
            new_name='ctzoffset',
        ),
        migrations.RenameField(
            model_name='escalationmatrix',
            old_name='tzoffset',
            new_name='ctzoffset',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='tzoffset',
            new_name='ctzoffset',
        ),
        migrations.RenameField(
            model_name='jobneeddetails',
            old_name='tzoffset',
            new_name='ctzoffset',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='tzoffset',
            new_name='ctzoffset',
        ),
        migrations.RenameField(
            model_name='questionset',
            old_name='tzoffset',
            new_name='ctzoffset',
        ),
        migrations.RenameField(
            model_name='questionsetbelonging',
            old_name='tzoffset',
            new_name='ctzoffset',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='tzoffset',
            new_name='ctzoffset',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tzoffset',
        ),
        migrations.RemoveField(
            model_name='jobneed',
            name='tzoffset',
        ),
        migrations.AlterField(
            model_name='job',
            name='ctzoffset',
            field=models.IntegerField(default=-1, verbose_name='TimeZone'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='ctzoffset',
            field=models.IntegerField(default=-1, verbose_name='TimeZone'),
        ),
    ]
