# Generated by Django 3.2 on 2022-04-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20220412_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobneed',
            name='ticketno',
        ),
    ]
