# Generated by Django 3.2.18 on 2023-07-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_location_iscritical'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asset',
            name='assetcode_client_uk',
        ),
        migrations.RemoveConstraint(
            model_name='location',
            name='loccode_client_uk',
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('assetcode', 'bu', 'client'), name='assetcode_client_uk'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('loccode', 'bu', 'client'), name='loccode_bu_client_uk'),
        ),
    ]
