# Generated by Django 3.2.14 on 2022-07-11 10:40

import django.contrib.gis.db.models.fields
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_asset_gpslocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='gpslocation',
            field = django.contrib.gis.db.models.fields.PointField(blank = True, geography = True, null = True, srid = 4326, verbose_name='GPS Location'),
        ),
    ]
