# Generated by Django 3.2 on 2022-05-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_attachment_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='serv_prov',
            new_name='servprov',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='asset',
        ),
        migrations.AlterField(
            model_name='question',
            name='answertype',
            field=models.CharField(choices=[('CHECKBOX', 'Checkbox'), ('DATE', 'Date'), ('DROPDOWN', 'Dropdown'), ('EMAILID', 'Email Id'), ('MULTILINE', 'Multiline'), ('NUMERIC', 'Numeric'), ('SIGNATURE', 'Signature'), ('SINGLELINE', 'Single Line'), ('TIME', 'Time'), ('RATING', 'Rating'), ('PEOPLELIST', 'People List'), ('SITELIST', 'Site List')], default='NUMERIC', max_length=55, verbose_name='Type'),
        ),
    ]
