# Generated by Django 3.1 on 2022-02-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20220201_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='frequency',
            field=models.CharField(choices=[('None', 'None'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Bimonthly', 'Bimonthly'), ('Quarterly', 'Quarterly'), ('Half Yearly', 'Halfyearly'), ('Yearly', 'Yearly'), ('Fort Nightly', 'Fortnightly')], max_length=55, null=True, verbose_name='Frequency type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='identifier',
            field=models.CharField(choices=[('Task', 'Task'), ('Ticket', 'Ticket'), ('Internal Tour', 'Internaltour'), ('External Tour', 'Externaltour'), ('PPM', 'Ppm'), ('Other', 'Other')], max_length=100, null=True, verbose_name='Job Type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=100, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='job',
            name='scantype',
            field=models.CharField(choices=[('QR', 'Qr'), ('NFC', 'Nfc'), ('Skip', 'Skip'), ('Entered', 'Entered')], max_length=50, verbose_name='Scan Type'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='frequency',
            field=models.CharField(choices=[('None', 'None'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Bimonthly', 'Bimonthly'), ('Quarterly', 'Quarterly'), ('Half Yearly', 'Halfyearly'), ('Yearly', 'Yearly'), ('Fort Nightly', 'Fortnightly')], max_length=55, null=True, verbose_name='Frequency type'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='identifier',
            field=models.CharField(choices=[('Task', 'Task'), ('Ticket', 'Ticket'), ('Internal Tour', 'Internaltour'), ('External Tour', 'Externaltour'), ('PPM', 'Ppm'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Jobneed Type'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='jobstatus',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Auto Closed', 'Autoclosed'), ('Completed', 'Completed'), ('Inprogress', 'Inprogress'), ('Partially Completed', 'Partiallycompleted')], max_length=60, null=True, verbose_name='Job Status'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='jobtype',
            field=models.CharField(choices=[('Schedule', 'Schedule'), ('Adhoc', 'Adhoc')], max_length=50, null=True, verbose_name='Job Type'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=50, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='scantype',
            field=models.CharField(choices=[('QR', 'Qr'), ('NFC', 'Nfc'), ('Skip', 'Skip'), ('Entered', 'Entered')], max_length=50, verbose_name='Scan type'),
        ),
        migrations.AlterField(
            model_name='jobneeddetails',
            name='answertype',
            field=models.CharField(choices=[('Checkbox', 'Checkbox'), ('Date', 'Date'), ('Dropdown', 'Dropdown'), ('Email Id', 'Emailid'), ('Multiline', 'Multiline'), ('Numeric', 'Numeric'), ('Signature', 'Signature'), ('Single Line', 'Singleline'), ('Time', 'Time'), ('Rating', 'Rating'), ('Back Camera', 'Backcamera'), ('Front Camera', 'Frontcamera'), ('People List', 'Peoplelist'), ('Site List', 'Sitelist')], max_length=50, null=True, verbose_name='Answer Type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answertype',
            field=models.CharField(choices=[('Checkbox', 'Checkbox'), ('Date', 'Date'), ('Dropdown', 'Dropdown'), ('Email Id', 'Emailid'), ('Multiline', 'Multiline'), ('Numeric', 'Numeric'), ('Signature', 'Signature'), ('Single Line', 'Singleline'), ('Time', 'Time'), ('Rating', 'Rating'), ('Back Camera', 'Backcamera'), ('Front Camera', 'Frontcamera'), ('People List', 'Peoplelist'), ('Site List', 'Sitelist')], default='NUMERIC', max_length=55, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='type',
            field=models.CharField(choices=[('Checklist', 'Checklist'), ('Incident Report Template', 'Incidentreporttemplate'), ('Site Report Template', 'Sitereporttemplate'), ('Work Permit Template', 'Workpermittemplate'), ('Kpi Template', 'Kpitemplate'), ('Scrapped Template', 'Scrappedtemplate'), ('Asset Audit', 'Assetaudit'), ('Maintenance Template', 'Maintenancetemplate'), ('Asset Maintenance', 'Assetmaintenance'), ('Question Set', 'Questionset')], max_length=50, null=True, verbose_name='Question Set Type'),
        ),
        migrations.AlterField(
            model_name='questionsetbelonging',
            name='answertype',
            field=models.CharField(choices=[('Checkbox', 'Checkbox'), ('Date', 'Date'), ('Dropdown', 'Dropdown'), ('Email Id', 'Emailid'), ('Multiline', 'Multiline'), ('Numeric', 'Numeric'), ('Signature', 'Signature'), ('Single Line', 'Singleline'), ('Time', 'Time'), ('Rating', 'Rating'), ('Back Camera', 'Backcamera'), ('Front Camera', 'Frontcamera'), ('People List', 'Peoplelist'), ('Site List', 'Sitelist')], max_length=50, verbose_name='Question Type'),
        ),
    ]
