# Generated by Django 3.2.14 on 2022-08-09 01:01

import apps.activity.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20220802_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='type',
            field=models.CharField(choices=[('CHECKLIST', 'Checklist'), ('INCIDENTREPORTTEMPLATE', 'Incident Report Template'), ('SITEREPORTTEMPLATE', 'Site Report Template'), ('WORKPERMITTEMPLATE', 'Work Permit Template'), ('RETURNWORKPERMITTEMPLATE', 'Return Work Permit Template'), ('KPITEMPLATE', 'Kpi Template'), ('SCRAPPEDTEMPLATE', 'Scrapped Template'), ('ASSETAUDIT', 'Asset Audit'), ('MAINTENANCETEMPLATE', 'Maintenance Template'), ('ASSETMAINTENANCE', 'Asset Maintenance'), ('QUESTIONSET', 'Question Set')], max_length=50, null=True, verbose_name='Question Set Type'),
        ),
    ]
