# Generated by Django 3.2.14 on 2022-07-13 07:16

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_asset_gpslocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attcount',
            field = models.IntegerField(default = 0, verbose_name='Attachment Count'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='parent',
            field = models.ForeignKey(blank = True, null = True, on_delete = django.db.models.deletion.RESTRICT, to='activity.ticket'),
        ),
    ]
