# Generated by Django 3.2 on 2022-04-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_remove_jobneed_ticketno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobneeddetails',
            old_name='slno',
            new_name='seqno',
        ),
        migrations.RenameField(
            model_name='questionsetbelonging',
            old_name='slno',
            new_name='seqno',
        ),
        migrations.AlterField(
            model_name='jobneeddetails',
            name='ismandatory',
            field=models.BooleanField(default=True, verbose_name='Is Mandatory'),
        ),
    ]
