# Generated by Django 3.2 on 2022-05-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20220514_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobneed',
            name='attcount',
            field=models.IntegerField(default=0, verbose_name='Attachment Count'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='ismailsent',
            field=models.BooleanField(default=False, verbose_name='Is Mail Sent'),
        ),
    ]
