# Generated by Django 3.2.14 on 2022-08-09 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0003_alter_people_gender'),
        ('activity', '0004_auto_20220809_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_sgroup', to='peoples.pgroup', verbose_name='Site Group'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='sgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneed_sgroup', to='peoples.pgroup', verbose_name='Site Group'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_pgroup', to='peoples.pgroup', verbose_name='People Group'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='pgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneed_pgroup', to='peoples.pgroup', verbose_name='People Group'),
        ),
    ]
