# Generated by Django 3.1 on 2022-02-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20220207_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='frequency',
            field=models.CharField(choices=[('NONE', 'None'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('BIMONTHLY', 'Bimonthly'), ('QUARTERLY', 'Quarterly'), ('HALFYEARLY', 'Half Yearly'), ('YEARLY', 'Yearly'), ('FORTNIGHTLY', 'Fort Nightly')], max_length=55, null=True, verbose_name='Frequency type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='identifier',
            field=models.CharField(choices=[('TASK', 'Task'), ('TICKET', 'Ticket'), ('INTERNALTOUR', 'Internal Tour'), ('EXTERNALTOUR', 'External Tour'), ('PPM', 'PPM'), ('OTHER', 'Other')], max_length=100, null=True, verbose_name='Job Type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('LOW', 'Low'), ('MEDIU', 'Medium')], max_length=100, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='job',
            name='scantype',
            field=models.CharField(choices=[('QR', 'QR'), ('NFC', 'NFC'), ('SKIP', 'Skip'), ('ENTERED', 'Entered')], max_length=50, verbose_name='Scan Type'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='frequency',
            field=models.CharField(choices=[('NONE', 'None'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('BIMONTHLY', 'Bimonthly'), ('QUARTERLY', 'Quarterly'), ('HALFYEARLY', 'Half Yearly'), ('YEARLY', 'Yearly'), ('FORTNIGHTLY', 'Fort Nightly')], max_length=55, null=True, verbose_name='Frequency type'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='identifier',
            field=models.CharField(choices=[('TASK', 'Task'), ('TICKET', 'Ticket'), ('INTERNALTOUR', 'Internal Tour'), ('EXTERNALTOUR', 'External Tour'), ('PPM', 'PPM'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Jobneed Type'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='jobstatus',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('AUTOCLOSED', 'Auto Closed'), ('COMPLETED', 'Completed'), ('INPROGRESS', 'Inprogress'), ('PARTIALLYCOMPLETED', 'Partially Completed')], max_length=60, null=True, verbose_name='Job Status'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='jobtype',
            field=models.CharField(choices=[('SCHEDULE', 'Schedule'), ('ADHOC', 'Adhoc')], max_length=50, null=True, verbose_name='Job Type'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('LOW', 'Low'), ('MEDIUM', 'Medium')], max_length=50, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='scantype',
            field=models.CharField(choices=[('NONE', 'None'), ('QR', 'QR'), ('NFC', 'NFC'), ('SKIP', 'Skip'), ('ENTERED', 'Entered')], max_length=50, verbose_name='Scan type'),
        ),
        migrations.AlterField(
            model_name='jobneeddetails',
            name='answertype',
            field=models.CharField(choices=[('CHECKBOX', 'Checkbox'), ('DATE', 'Date'), ('DROPDOWN', 'Dropdown'), ('EMAILID', 'Email Id'), ('MULTILINE', 'Multiline'), ('NUMERIC', 'Numeric'), ('SIGNATURE', 'Signature'), ('SINGLELINE', 'Single Line'), ('TIME', 'Time'), ('RATING', 'Rating'), ('BACKCAMERA', 'Back Camera'), ('FRONTCAMERA', 'Front Camera'), ('PEOPLELIST', 'People List'), ('SITELIST', 'Site List')], max_length=50, null=True, verbose_name='Answer Type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answertype',
            field=models.CharField(choices=[('CHECKBOX', 'Checkbox'), ('DATE', 'Date'), ('DROPDOWN', 'Dropdown'), ('EMAILID', 'Email Id'), ('MULTILINE', 'Multiline'), ('NUMERIC', 'Numeric'), ('SIGNATURE', 'Signature'), ('SINGLELINE', 'Single Line'), ('TIME', 'Time'), ('RATING', 'Rating'), ('BACKCAMERA', 'Back Camera'), ('FRONTCAMERA', 'Front Camera'), ('PEOPLELIST', 'People List'), ('SITELIST', 'Site List')], default='NUMERIC', max_length=55, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='type',
            field=models.CharField(choices=[('CHECKLIST', 'Checklist'), ('INCIDENTREPORTTEMPLATE', 'Incident Report Template'), ('SITEREPORTTEMPLATE', 'Site Report Template'), ('WORKPERMITTEMPLATE', 'Work Permit Template'), ('KPITEMPLATE', 'Kpi Template'), ('SCRAPPEDTEMPLATE', 'Scrapped Template'), ('ASSETAUDIT', 'Asset Audit'), ('MAINTENANCETEMPLATE', 'Maintenance Template'), ('ASSETMAINTENANCE', 'Asset Maintenance'), ('QUESTIONSET', 'Question Set')], max_length=50, null=True, verbose_name='Question Set Type'),
        ),
        migrations.AlterField(
            model_name='questionsetbelonging',
            name='answertype',
            field=models.CharField(choices=[('CHECKBOX', 'Checkbox'), ('DATE', 'Date'), ('DROPDOWN', 'Dropdown'), ('EMAILID', 'Email Id'), ('MULTILINE', 'Multiline'), ('NUMERIC', 'Numeric'), ('SIGNATURE', 'Signature'), ('SINGLELINE', 'Single Line'), ('TIME', 'Time'), ('RATING', 'Rating'), ('BACKCAMERA', 'Back Camera'), ('FRONTCAMERA', 'Front Camera'), ('PEOPLELIST', 'People List'), ('SITELIST', 'Site List')], max_length=50, verbose_name='Question Type'),
        ),
    ]
