# Generated by Django 3.2.18 on 2023-09-01 06:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20230714_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobneed',
            name='journeypath',
            field=django.contrib.gis.db.models.fields.LineStringField(geography=True, null=True, srid=4326),
        ),
    ]
