# Generated by Django 3.2.14 on 2022-09-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20220809_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Enable'),
        ),
        migrations.AlterField(
            model_name='deviceeventlog',
            name='eventvalue',
            field=models.CharField(choices=[('STEPCOUNT', 'Step Count'), ('AIRPLANEMODEON', 'Airplanemode On'), ('AIRPLANEMODEOFF', 'Airplanemode Off'), ('PHONESWITCHEDON', 'PhoneSwitched On'), ('PHONESWITCHEDOFF', 'PhoneSwitched Off'), ('GPSSWITCHEDON', 'Gps Switched On'), ('GPSSWITCHEDOFF', 'Gps Switched Off'), ('WIFIENABLE', 'WIFI Enable'), ('WIFIDISABLE', 'WIFI Disable'), ('MOBILEDATAENABLE', 'MobileData Enable'), ('MOBILEDATADISABLE', 'MobileData Disable')], max_length=50, verbose_name='Device Event'),
        ),
    ]
