# Generated by Django 3.1 on 2022-01-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20220119_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionsetbelonging',
            old_name='seqno',
            new_name='slno',
        ),
        migrations.RemoveField(
            model_name='jobneed',
            name='seqno',
        ),
        migrations.RemoveField(
            model_name='jobneeddetails',
            name='seqno',
        ),
        migrations.AddField(
            model_name='jobneed',
            name='slno',
            field=models.SmallIntegerField(default=-1, verbose_name='Sl No.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobneeddetails',
            name='slno',
            field=models.SmallIntegerField(default=-1, verbose_name='SL No.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('BIMONTHLY', 'Bimonthly'), ('QUARTERLY', 'Quarterly'), ('HALFYEARLY', 'Half Yearly'), ('YEARLY', 'Yearly'), ('FORTNIGHTLY', 'Fort Nightly')], max_length=55, null=True, verbose_name='Frequency type'),
        ),
    ]
