# Generated by Django 3.2 on 2022-05-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20220523_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobneeddetails',
            name='attcount',
            field=models.IntegerField(default=0, verbose_name='Attachment count'),
        ),
    ]
