# Generated by Django 3.1 on 2022-02-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20220208_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='identifier',
            field=models.CharField(choices=[('TASK', 'Task'), ('TICKET', 'Ticket'), ('INTERNALTOUR', 'Internal Tour'), ('EXTERNALTOUR', 'External Tour'), ('PPM', 'PPM'), ('OTHER', 'Other'), ('INCIDENTREPORT', 'Incident Report'), ('ASSETLOG', 'Asset Log'), ('ASSETMAINTENANCE', 'Asset Maintenance')], max_length=100, null=True, verbose_name='Job Type'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='identifier',
            field=models.CharField(choices=[('TASK', 'Task'), ('TICKET', 'Ticket'), ('INTERNALTOUR', 'Internal Tour'), ('EXTERNALTOUR', 'External Tour'), ('PPM', 'PPM'), ('OTHER', 'Other'), ('INCIDENTREPORT', 'Incident Report'), ('ASSETLOG', 'Asset Log'), ('ASSETMAINTENANCE', 'Asset Maintenance')], max_length=50, null=True, verbose_name='Jobneed Type'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='jobstatus',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('AUTOCLOSED', 'Auto Closed'), ('COMPLETED', 'Completed'), ('INPROGRESS', 'Inprogress'), ('PARTIALLYCOMPLETED', 'Partially Completed'), ('RESOLVED', 'Resolved'), ('OPEN', 'Open'), ('CANCELLED', 'Cancelled'), ('ESCALATED', 'Escalated'), ('NEW', 'New'), ('MAINTENANCE', 'Maintenance'), ('STANDBY', 'Standby'), ('WORKING', 'Working'), ('SCRAPPED', 'Scrapped')], max_length=60, null=True, verbose_name='Job Status'),
        ),
    ]
