# Generated by Django 3.2 on 2022-04-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20220420_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobneed',
            old_name='slno',
            new_name='seqno',
        ),
    ]
