# Generated by Django 3.2.18 on 2023-09-01 06:02

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_jobneed_journeypath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobneed',
            name='journeypath',
            field=django.contrib.gis.db.models.fields.LineStringField(default=None, geography=True, null=True, srid=4326),
        ),
    ]
