# Generated by Django 3.2 on 2022-05-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_jobneeddetails_attcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobneed',
            old_name='attcount',
            new_name='attachmentcount',
        ),
        migrations.RenameField(
            model_name='jobneeddetails',
            old_name='attcount',
            new_name='attachmentcount',
        ),
    ]
