# Generated by Django 3.2 on 2022-04-23 09:28

import apps.activity.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_rename_slno_jobneed_seqno'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='attachment',
            managers=[
                ('objects', apps.activity.managers.AttachmentManager()),
            ],
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='isavpt',
            field=models.BooleanField(default=False, verbose_name='Is Attachment Required'),
        ),
    ]
