# Generated by Django 3.1 on 2022-02-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_auto_20220210_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='identifier',
            field=models.CharField(choices=[('TASK', 'Task'), ('TICKET', 'Ticket'), ('INTERNALTOUR', 'Internal Tour'), ('EXTERNALTOUR', 'External Tour'), ('PPM', 'PPM'), ('OTHER', 'Other'), ('SITEREPORT', 'Site Report'), ('INCIDENTREPORT', 'Incident Report'), ('ASSETLOG', 'Asset Log'), ('ASSETMAINTENANCE', 'Asset Maintenance')], max_length=100, null=True, verbose_name='Job Type'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='identifier',
            field=models.CharField(choices=[('TASK', 'Task'), ('TICKET', 'Ticket'), ('INTERNALTOUR', 'Internal Tour'), ('EXTERNALTOUR', 'External Tour'), ('PPM', 'PPM'), ('OTHER', 'Other'), ('SITEREPORT', 'Site Report'), ('INCIDENTREPORT', 'Incident Report'), ('ASSETLOG', 'Asset Log'), ('ASSETMAINTENANCE', 'Asset Maintenance')], max_length=50, null=True, verbose_name='Jobneed Type'),
        ),
    ]
