# Generated by Django 3.2.14 on 2022-10-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_auto_20220912_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobneeddetails',
            name='avpttype',
            field=models.CharField(blank=True, choices=[('BACKCAMPIC', 'Back Camera Pic'), ('FRONTCAMPIC', 'Front Camera Pic'), ('AUDIO', 'Audio'), ('VIDEO', 'Video')], max_length=50, null=True, verbose_name='Attachment Type'),
        ),
        migrations.AddField(
            model_name='question',
            name='avpttype',
            field=models.CharField(blank=True, choices=[('BACKCAMPIC', 'Back Camera Pic'), ('FRONTCAMPIC', 'Front Camera Pic'), ('AUDIO', 'Audio'), ('VIDEO', 'Video')], max_length=50, null=True, verbose_name='Attachment Type'),
        ),
        migrations.AddField(
            model_name='question',
            name='isavpt',
            field=models.BooleanField(default=False, verbose_name='Is Attachment Required'),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='avpttype',
            field=models.CharField(blank=True, choices=[('BACKCAMPIC', 'Back Camera Pic'), ('FRONTCAMPIC', 'Front Camera Pic'), ('AUDIO', 'Audio'), ('VIDEO', 'Video')], max_length=50, null=True, verbose_name='Attachment Type'),
        ),
    ]
