# Generated by Django 3.1 on 2022-01-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_auto_20220119_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionset',
            name='seqno',
        ),
        migrations.AddField(
            model_name='questionset',
            name='slno',
            field=models.SmallIntegerField(default=1, verbose_name='SL No.'),
        ),
    ]
