# Generated by Django 3.1 on 2022-02-11 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_auto_20220211_1222'),
        ('activity', '0007_auto_20220210_1509'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='job',
            name='jobname_assetid_qset_id_parent_identifier_uk',
        ),
        migrations.RemoveConstraint(
            model_name='question',
            name='ques_name_type_clientid_uk',
        ),
        migrations.RemoveConstraint(
            model_name='questionset',
            name='name_type_parent_type_clientid_buid_uk',
        ),
        migrations.RemoveConstraint(
            model_name='questionsetbelonging',
            name='qsetid_quesid_clientid_buid_uk',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='assetid',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='gfid',
            new_name='geofence',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='peopleid',
            new_name='people',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='groupid',
            new_name='pgroup',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='qsetid',
            new_name='qset',
        ),
        migrations.RenameField(
            model_name='jobneed',
            old_name='jobid',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='jobneed',
            old_name='peopleid',
            new_name='people',
        ),
        migrations.RenameField(
            model_name='jobneed',
            old_name='groupid',
            new_name='pgroup',
        ),
        migrations.RenameField(
            model_name='jobneed',
            old_name='qsetid',
            new_name='qset',
        ),
        migrations.RenameField(
            model_name='jobneeddetails',
            old_name='jobneedid',
            new_name='jobneed',
        ),
        migrations.RenameField(
            model_name='jobneeddetails',
            old_name='quesid',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='clientid',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='questionset',
            old_name='assetid',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='questionsetbelonging',
            old_name='qsetid',
            new_name='qset',
        ),
        migrations.RenameField(
            model_name='questionsetbelonging',
            old_name='quesid',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='buid',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='clientid',
        ),
        migrations.RemoveField(
            model_name='job',
            name='buid',
        ),
        migrations.RemoveField(
            model_name='job',
            name='clientid',
        ),
        migrations.RemoveField(
            model_name='jobneed',
            name='assetid',
        ),
        migrations.RemoveField(
            model_name='jobneed',
            name='buid',
        ),
        migrations.RemoveField(
            model_name='jobneed',
            name='clientid',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='buid',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='clientid',
        ),
        migrations.RemoveField(
            model_name='questionsetbelonging',
            name='buid',
        ),
        migrations.RemoveField(
            model_name='questionsetbelonging',
            name='clientid',
        ),
        migrations.AddField(
            model_name='asset',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_bus', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='asset',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_clients', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='job',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_bus', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='job',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_clients', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneed_assets', to='activity.asset', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneedf_bus', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneed_clients', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='qset_bus', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='qset_clients', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='qsetbelong_bu', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='qsetbelong_client', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('jobname', 'asset', 'qset', 'parent', 'identifier'), name='jobname_asset_qset_id_parent_identifier_uk'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('ques_name', 'answertype', 'client'), name='ques_name_type_client_uk'),
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.UniqueConstraint(fields=('qset_name', 'parent', 'type', 'client', 'bu'), name='name_type_parent_type_client_bu_uk'),
        ),
        migrations.AddConstraint(
            model_name='questionsetbelonging',
            constraint=models.UniqueConstraint(fields=('qset', 'question', 'client', 'bu'), name='qset_question_client_bu_uk'),
        ),
    ]
