# Generated by Django 3.2.14 on 2022-10-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20221015_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='avpttype',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('BACKCAMPIC', 'Back Camera Pic'), ('FRONTCAMPIC', 'Front Camera Pic'), ('AUDIO', 'Audio'), ('VIDEO', 'Video')], max_length=50, null=True, verbose_name='Attachment Type'),
        ),
    ]
