# Generated by Django 3.1 on 2022-01-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20220119_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='aaatop',
            new_name='peopleid',
        ),
        migrations.RemoveField(
            model_name='job',
            name='aatop',
        ),
        migrations.RemoveField(
            model_name='jobneed',
            name='aatop',
        ),
    ]
