# Generated by Django 3.2 on 2022-04-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20220423_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobneeddetails',
            name='isavpt',
            field=models.BooleanField(default=False, verbose_name='Is Attachement Required'),
        ),
    ]
