# Generated by Django 3.2 on 2022-05-26 07:15

import apps.peoples.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0003_auto_20220503_1533'),
        ('activity', '0007_auto_20220523_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceEventlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='mdtz')),
                ('ctzoffset', models.IntegerField(default=-1, verbose_name='TimeZone')),
                ('deviceid', models.CharField(max_length=55, verbose_name='Device Id')),
                ('deviceevent', models.CharField(choices=[('AIRPLANEMODEON', 'Airplanemode On'), ('AIRPLANEMODEOFF', 'Airplanemode Off'), ('PHONESWITCHEDON', 'PhoneSwitched On'), ('PHONESWITCHEDOFF', 'PhoneSwitched Off'), ('GPSSWITCHEDON', 'Gps Switched On'), ('GPSSWITCHEDOFF', 'Gps Switched Off'), ('WIFIENABLE', 'WIFI Enable'), ('WIFIDISABLE', 'WIFI Disable'), ('MOBILEDATAENABLE', 'MobileData Enable'), ('MOBILEDATADISABLE', 'MobileData Disable')], max_length=50, verbose_name='Device Event')),
                ('receivedon', models.DateTimeField(auto_now_add=True, verbose_name='Received On')),
                ('stepcount', models.CharField(default='NONE', max_length=55)),
                ('bu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='deviveevents_clients', to='onboarding.bt', verbose_name='Client')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='deviceeventlog_cusers', to=settings.AUTH_USER_MODEL)),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='deviceeventlog_musers', to=settings.AUTH_USER_MODEL)),
                ('people', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='deviceevent_people', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['mdtz'],
                'abstract': False,
            },
        ),
    ]
