# Generated by Django 3.2.18 on 2023-09-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_alter_jobneed_journeypath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='loccode',
            field=models.CharField(max_length=50, verbose_name='Asset Code'),
        ),
    ]
