# Generated by Django 3.2 on 2022-04-27 09:22

import apps.activity.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_jobneeddetails_isavpt'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='asset',
            managers=[
                ('objects', apps.activity.managers.AssetManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='jobneeddetails',
            managers=[
                ('objects', apps.activity.managers.JobneedDetailsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('objects', apps.activity.managers.QuestionManager()),
            ],
        ),
        migrations.RenameField(
            model_name='questionset',
            old_name='slno',
            new_name='seqno',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('CANCEL', 'Cancel'), ('CLOSE', 'Close'), ('ESCALATED', 'Escalated'), ('AUTOCLOSE', 'Autoclose'), ('ASSIGNED', 'Assigned')], max_length=50, null=True, verbose_name='Status'),
        ),
    ]
