# Generated by Django 3.2.14 on 2022-11-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_alter_question_avpttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionset',
            name='site_grp_includes',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='site_type_includes',
        ),
    ]
