# Generated by Django 3.2 on 2022-05-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_deviceeventlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceeventlog',
            options={'get_latest_by': ['mdtz', 'cdtz'], 'ordering': ['mdtz']},
        ),
        migrations.AlterModelTable(
            name='deviceeventlog',
            table='deviceeventlog',
        ),
    ]
