# Generated by Django 3.1 on 2022-01-22 05:07

import apps.activity.models
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_auto_20220119_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobneed',
            name='raisedtktflag',
        ),
        migrations.AddField(
            model_name='job',
            name='other_info',
            field=models.JSONField(blank=True, default=apps.activity.models.other_info, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Other info'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='other_info',
            field=models.JSONField(blank=True, default=apps.activity.models.other_info, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Other info'),
        ),
    ]
