# Generated by Django 3.2.14 on 2022-11-01 07:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_auto_20221101_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='site_grp_includes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, null=True, size=None, verbose_name='Site Group Includes'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='site_type_includes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, null=True, size=None, verbose_name='Site Type Includes'),
        ),
    ]
