# Generated by Django 3.1 on 2022-01-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_auto_20220122_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobneed',
            name='raisedtktflag',
            field=models.BooleanField(default=False, null=True, verbose_name='RaiseTicketFlag'),
        ),
    ]
