# Generated by Django 3.2 on 2022-04-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_auto_20220427_1452'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questionset',
            name='slno_gte_0_ck',
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.CheckConstraint(check=models.Q(seqno__gte=0), name='slno_gte_0_ck'),
        ),
    ]
