# Generated by Django 3.1 on 2022-02-14 11:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_auto_20220211_1222'),
        ('activity', '0009_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='attachmenttype',
            field=models.CharField(choices=[('NONE', 'NONE'), ('ATTACHMENT', 'Attachment'), ('REPLY', 'Reply'), ('SIGN', 'SIGN')], default='NONE', max_length=55),
        ),
        migrations.AddField(
            model_name='attachment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 17, 5, 23, 186395)),
        ),
        migrations.AddField(
            model_name='attachment',
            name='gpslocation',
            field=models.CharField(default='0.0,0.0', max_length=50, verbose_name='Gps Location'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='owner',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='ownername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.typeassist'),
        ),
    ]
