# Generated by Django 3.2 on 2022-06-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_auto_20220526_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='identifier',
            field=models.CharField(choices=[('TASK', 'Task'), ('TICKET', 'Ticket'), ('INTERNALTOUR', 'Internal Tour'), ('EXTERNALTOUR', 'External Tour'), ('PPM', 'PPM'), ('OTHER', 'Other'), ('SITEREPORT', 'Site Report'), ('INCIDENTREPORT', 'Incident Report'), ('ASSETLOG', 'Asset Log'), ('ASSETMAINTENANCE', 'Asset Maintenance'), ('GEOFENCE', 'Geofence')], max_length=100, null=True, verbose_name='Job Type'),
        ),
    ]
