# Generated by Django 3.2 on 2022-04-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_auto_20220427_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobneeddetails',
            name='answer',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='Answer'),
        ),
    ]
