# Generated by Django 3.1 on 2022-02-14 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_auto_20220214_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 11, 36, 27, 503983)),
        ),
    ]
