# Generated by Django 3.1 on 2022-01-22 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_auto_20220122_1132'),
        ('activity', '0010_jobneed_raisedtktflag'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questionset',
            name='name_type_parent_type_clientid_siteid_uk',
        ),
        migrations.RemoveConstraint(
            model_name='questionsetbelonging',
            name='qsetid_quesid_clientid_siteid_uk',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='siteid',
        ),
        migrations.RemoveField(
            model_name='job',
            name='siteid',
        ),
        migrations.RemoveField(
            model_name='jobneed',
            name='siteid',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='siteid',
        ),
        migrations.RemoveField(
            model_name='questionsetbelonging',
            name='siteid',
        ),
        migrations.AddField(
            model_name='asset',
            name='buid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_buids', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='job',
            name='buid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_buids', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='buid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneedf_buids', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='buid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='qset_buids', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='buid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='qsetbelong_buid', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.UniqueConstraint(fields=('qset_name', 'parent', 'type', 'clientid', 'buid'), name='name_type_parent_type_clientid_buid_uk'),
        ),
        migrations.AddConstraint(
            model_name='questionsetbelonging',
            constraint=models.UniqueConstraint(fields=('qsetid', 'quesid', 'clientid', 'buid'), name='qsetid_quesid_clientid_buid_uk'),
        ),
    ]
