# Generated by Django 3.2 on 2022-06-07 05:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_alter_job_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='assetincludes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, null=True, size=None, verbose_name='Asset Includes'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='buincludes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, null=True, size=None, verbose_name='Bu Includes'),
        ),
    ]
