# Generated by Django 3.2.14 on 2022-11-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_auto_20221101_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cron',
            field=models.CharField(default='* * * * *', max_length=200, verbose_name='Cron Exp.'),
        ),
    ]
