# Generated by Django 3.2.18 on 2023-12-07 07:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_auto_20231207_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobneed',
            name='journeypath',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
