# Generated by Django 3.1 on 2022-01-22 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_auto_20220122_1132'),
        ('activity', '0011_auto_20220122_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_shifts', to='onboarding.shift', verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='job',
            name='identifier',
            field=models.CharField(choices=[('TASK', 'Task'), ('TICKET', 'Ticket'), ('INTERNALTOUR', 'Internal Tour'), ('EXTERNALTOUR', 'External Tour'), ('PPM', 'PPM'), ('OTHER', 'Other')], max_length=100, null=True, verbose_name='Job Type'),
        ),
    ]
