# Generated by Django 3.1 on 2022-02-19 05:42

import apps.activity.managers
import apps.activity.models
import datetime
from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
        ('onboarding', '0003_auto_20220211_1222'),
        ('peoples', '0002_auto_20220211_1222'),
        ('activity', '0011_auto_20220214_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(auto_now_add=True, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(auto_now=True, verbose_name='mdtz')),
                ('devicecode', models.CharField(max_length=50)),
                ('devicename', models.CharField(max_length=50)),
                ('enable', models.BooleanField(default=True)),
                ('devicedesc', models.CharField(max_length=50, null=True)),
                ('ipaddress', models.CharField(blank=True, max_length=100, null=True)),
                ('belongsTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.device')),
                ('bu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='device_cusers', to=settings.AUTH_USER_MODEL)),
                ('devicetype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='device_types', to='onboarding.typeassist')),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='device_musers', to=settings.AUTH_USER_MODEL)),
                ('runningStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='device_status', to='onboarding.typeassist')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'device',
                'ordering': ['mdtz'],
                'get_latest_by': ['mdtz', 'cdtz'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(auto_now_add=True, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(auto_now=True, verbose_name='mdtz')),
                ('eventdesc', models.CharField(blank=True, max_length=250, null=True)),
                ('eventdatetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('bu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='event_cusers', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='event_device', to='activity.device')),
                ('eventtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='event_types', to='onboarding.typeassist')),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='event_musers', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'event',
                'ordering': ['mdtz'],
                'get_latest_by': ['cdtz', 'mdtz'],
                'abstract': False,
            },
        ),
        migrations.AlterModelManagers(
            name='questionset',
            managers=[
                ('objects', apps.activity.managers.QuestionSetManager()),
            ],
        ),
        migrations.AlterField(
            model_name='attachment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(auto_now_add=True, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(auto_now=True, verbose_name='mdtz')),
                ('ticketno', models.IntegerField(default=0, null=True, unique=True, verbose_name='Ticket No')),
                ('comments', models.TextField(max_length=1000, null=True)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('LOW', 'Low'), ('MEDIUM', 'Medium')], default='MEDIUM', max_length=50, verbose_name='Priority')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.IntegerField(default=-1, verbose_name='Level')),
                ('status', models.CharField(default='NEW', max_length=50, verbose_name='Tickert')),
                ('ticket_history', models.JSONField(default=apps.activity.models.tickethistory, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='History')),
                ('ticketsource', models.CharField(choices=[('USERDEFINED', 'User Defined'), ('SYSDEFINED', 'System Defined')], default='SYSDEFINED', max_length=55)),
                ('assignedgrp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='peoples.pgroup', verbose_name='Assigned Group')),
                ('assignedpeople', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_assgd_peoples', to=settings.AUTH_USER_MODEL, verbose_name='Assigned People')),
                ('bu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_cusers', to=settings.AUTH_USER_MODEL)),
                ('esc_tempate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.typeassist')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.event')),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_musers', to=settings.AUTH_USER_MODEL)),
                ('performedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='performedby', to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['mdtz'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EscalationMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(auto_now_add=True, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(auto_now=True, verbose_name='mdtz')),
                ('body', models.CharField(max_length=50, null=True, verbose_name='Body')),
                ('level', models.SmallIntegerField(verbose_name='Level')),
                ('frequency_value', models.IntegerField(verbose_name='Frequency Value')),
                ('notify', models.TextField(max_length=1000, null=True)),
                ('assignedgrp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='peoples.pgroup', verbose_name='Assigned Group')),
                ('assignedpeople', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='esc_assgd_peoples', to=settings.AUTH_USER_MODEL, verbose_name='Assigned People')),
                ('bu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='escalationmatrix_cusers', to=settings.AUTH_USER_MODEL)),
                ('esctemplate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.typeassist')),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='escalationmatrix_musers', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['mdtz'],
                'abstract': False,
            },
        ),
    ]
