# Generated by Django 3.2 on 2022-06-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_auto_20220607_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='identifier',
            field=models.CharField(choices=[('NONE', 'None'), ('ASSET', 'Asset'), ('CHECKPOINT', 'Checkpoint'), ('LOCATION', 'Location'), ('SMARTPLACE', 'Smartplace'), ('NEA', 'Non Engineering Asset')], default='NONE', max_length=55, verbose_name='Asset Identifier'),
        ),
        migrations.AlterField(
            model_name='job',
            name='frequency',
            field=models.CharField(choices=[('NONE', 'None'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('BIMONTHLY', 'Bimonthly'), ('QUARTERLY', 'Quarterly'), ('HALFYEARLY', 'Half Yearly'), ('YEARLY', 'Yearly'), ('FORTNIGHTLY', 'Fort Nightly')], default='NONE', max_length=55, null=True, verbose_name='Frequency type'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='frequency',
            field=models.CharField(choices=[('NONE', 'None'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('BIMONTHLY', 'Bimonthly'), ('QUARTERLY', 'Quarterly'), ('HALFYEARLY', 'Half Yearly'), ('YEARLY', 'Yearly'), ('FORTNIGHTLY', 'Fort Nightly')], default='NONE', max_length=55, null=True, verbose_name='Frequency type'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='scantype',
            field=models.CharField(choices=[('NONE', 'None'), ('QR', 'QR'), ('NFC', 'NFC'), ('SKIP', 'Skip'), ('ENTERED', 'Entered')], default='NONE', max_length=50, verbose_name='Scan type'),
        ),
    ]
