# Generated by Django 3.2.14 on 2022-12-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_alter_job_cron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobneeddetails',
            name='avpttype',
            field=models.CharField(blank=True, choices=[('BACKCAMPIC', 'Back Camera Pic'), ('FRONTCAMPIC', 'Front Camera Pic'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('NONE', 'NONE')], max_length=50, null=True, verbose_name='Attachment Type'),
        ),
        migrations.AlterField(
            model_name='questionsetbelonging',
            name='avpttype',
            field=models.CharField(blank=True, choices=[('BACKCAMPIC', 'Back Camera Pic'), ('FRONTCAMPIC', 'Front Camera Pic'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('NONE', 'NONE')], max_length=50, null=True, verbose_name='Attachment Type'),
        ),
    ]
