# Generated by Django 3.1 on 2022-02-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_auto_20220219_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escalationmatrix',
            old_name='frequency_value',
            new_name='frequencyvalue',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='assignedgrp',
            new_name='assignedgroup',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='esc_tempate',
            new_name='esctemplate',
        ),
        migrations.AddField(
            model_name='escalationmatrix',
            name='frequency',
            field=models.CharField(choices=[('MINUTE', 'MINUTE'), ('HOUR', 'HOUR'), ('DAY', 'DAY'), ('WEEK', 'WEEK')], default='MINUTE', max_length=50, verbose_name='Frequency'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticketdesc',
            field=models.TextField(max_length=1000, null=True, verbose_name='Ticket Desc'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='NEW', max_length=50, verbose_name='Ticket'),
        ),
    ]
