# Generated by Django 3.1 on 2022-01-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_auto_20220122_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ctzoffset',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='TZ_Offset'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='ctzoffset',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='TZ_Offset'),
        ),
    ]
