# Generated by Django 3.2 on 2022-06-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_auto_20220627_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceeventlog',
            name='androidversion',
            field=models.CharField(default=None, max_length=50, verbose_name='Android Version'),
        ),
        migrations.AddField(
            model_name='deviceeventlog',
            name='appversion',
            field=models.CharField(default=None, max_length=50, verbose_name='App Version'),
        ),
        migrations.AddField(
            model_name='deviceeventlog',
            name='availextmemory',
            field=models.CharField(default=None, max_length=50, verbose_name='Available External Memory'),
        ),
        migrations.AddField(
            model_name='deviceeventlog',
            name='availintmemory',
            field=models.CharField(default=None, max_length=50, verbose_name='Available Internal Memory'),
        ),
        migrations.AddField(
            model_name='deviceeventlog',
            name='batterylevel',
            field=models.CharField(default=None, max_length=50, verbose_name='Battery Level'),
        ),
        migrations.AddField(
            model_name='deviceeventlog',
            name='installedapps',
            field=models.CharField(default=None, max_length=50, verbose_name='Installed Apps'),
        ),
        migrations.AddField(
            model_name='deviceeventlog',
            name='modelname',
            field=models.CharField(default=None, max_length=50, verbose_name='Model Name'),
        ),
        migrations.AddField(
            model_name='deviceeventlog',
            name='signalbandwidth',
            field=models.CharField(default=None, max_length=50, verbose_name='Signal Bandwidth'),
        ),
        migrations.AddField(
            model_name='deviceeventlog',
            name='signalstrength',
            field=models.CharField(default=None, max_length=50, verbose_name='Signal Strength'),
        ),
        migrations.AlterField(
            model_name='deviceeventlog',
            name='stepcount',
            field=models.CharField(default='No Steps', max_length=55),
        ),
    ]
