# Generated by Django 3.2.18 on 2023-12-08 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_auto_20231207_0056'),
        ('activity', '0012_alter_jobneed_journeypath'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobneed',
            name='remarks_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='remark_types', to='onboarding.typeassist'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remark'),
        ),
    ]
