# Generated by Django 3.2.14 on 2022-12-14 07:28

import apps.activity.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_auto_20221212_1246'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ticket',
            managers=[
                ('objects', apps.y_helpdesk.managers.TicketManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='attachmentcount',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='uuid',
        ),
        migrations.AddField(
            model_name='job',
            name='deviation',
            field=models.BooleanField(default=False, verbose_name='Deviation'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='events',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketsource',
            field=models.CharField(blank=True, choices=[('SYSTEMGENERATED', 'New Generated'), ('USERDEFINED', 'User Defined')], max_length=50, null=True),
        ),
    ]
