# Generated by Django 3.2.18 on 2023-12-08 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_auto_20231208_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobneed',
            old_name='remarks_type',
            new_name='remarkstype',
        ),
    ]
