# Generated by Django 3.1 on 2022-02-28 07:42

import apps.activity.models
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0002_auto_20220211_1222'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0013_auto_20220220_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalationmatrix',
            options={'get_latest_by': ['mdtz', 'cdtz'], 'ordering': ['mdtz']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'get_latest_by': ['cdtz', 'mdtz'], 'ordering': ['mdtz']},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='modified_date',
            new_name='modifieddatetime',
        ),
        migrations.RemoveField(
            model_name='escalationmatrix',
            name='assignedgrp',
        ),
        migrations.RemoveField(
            model_name='escalationmatrix',
            name='assignedpeople',
        ),
        migrations.RemoveField(
            model_name='escalationmatrix',
            name='esctemplate',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assignedgroup',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assignedpeople',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='esctemplate',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_history',
        ),
        migrations.AddField(
            model_name='escalationmatrix',
            name='assignedfor',
            field=models.CharField(default=-1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escalationmatrix',
            name='assignedgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='escalation_grps', to='peoples.pgroup'),
        ),
        migrations.AddField(
            model_name='escalationmatrix',
            name='assignedperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='escalation_people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalationmatrix',
            name='escalationtemplate',
            field=models.CharField(default=-1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='assignedtogroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_grps', to='peoples.pgroup'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assignedtopeople',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalationtemplate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='isescalated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticketlog',
            field=models.JSONField(blank=True, default=apps.activity.models.ticket_defaults, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='gpslocation',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='GPS Location'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='gpslocation',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='GPS Location'),
        ),
        migrations.AlterField(
            model_name='escalationmatrix',
            name='body',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='escalationmatrix',
            name='frequency',
            field=models.CharField(choices=[('MINUTE', 'MINUTE'), ('HOUR', 'HOUR'), ('DAY', 'DAY'), ('WEEK', 'WEEK')], default='DAY', max_length=10),
        ),
        migrations.AlterField(
            model_name='escalationmatrix',
            name='frequencyvalue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escalationmatrix',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escalationmatrix',
            name='notify',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='gpslocation',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='GPS Location'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='comments',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='performedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_performedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(blank=True, choices=[('HIGH', 'High'), ('LOW', 'Low'), ('MEDIUM', 'Medium')], max_length=50, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('CANCEL', 'Cancel'), ('CLOSE', 'Close'), ('ESCALATED', 'Escalated'), ('ASSIGNED', 'Assigned')], max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketdesc',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketsource',
            field=models.CharField(blank=True, choices=[('SYSTEMGENERATED', 'System Generated'), ('USERDEFINED', 'User Defined')], max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('bu', 'ticketno'), name='bu_ticketno_uk'),
        ),
        migrations.AlterModelTable(
            name='escalationmatrix',
            table='escalationmatrix',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='ticket',
        ),
    ]
