# Generated by Django 3.1 on 2022-01-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_auto_20220124_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobneed',
            name='frequency',
            field=models.CharField(choices=[('NONE', 'NONE'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('BIMONTHLY', 'Bimonthly'), ('QUARTERLY', 'Quarterly'), ('HALFYEARLY', 'Half Yearly'), ('YEARLY', 'Yearly'), ('FORTNIGHTLY', 'Fort Nightly')], max_length=55, null=True, verbose_name='Frequency type'),
        ),
    ]
