# Generated by Django 3.2.14 on 2022-12-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_auto_20221214_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='deviation',
        ),
        migrations.AddField(
            model_name='jobneed',
            name='deviation',
            field=models.BooleanField(default=False, verbose_name='Deviation'),
        ),
    ]
