# Generated by Django 3.2.18 on 2023-12-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_rename_remarks_type_jobneed_remarkstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobneed',
            name='expirydatetime',
            field=models.DateTimeField(null=True, verbose_name='Expiry date time'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='plandatetime',
            field=models.DateTimeField(null=True, verbose_name='Plan date time'),
        ),
    ]
