# Generated by Django 3.2.14 on 2022-12-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_auto_20221214_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobneed',
            name='deviation',
            field=models.BooleanField(default=False, null=True, verbose_name='Deviation'),
        ),
    ]
