# Generated by Django 3.2.18 on 2024-02-01 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_auto_20231228_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bu',
        ),
        migrations.RemoveField(
            model_name='event',
            name='cuser',
        ),
        migrations.RemoveField(
            model_name='event',
            name='device',
        ),
        migrations.RemoveField(
            model_name='event',
            name='eventtype',
        ),
        migrations.RemoveField(
            model_name='event',
            name='muser',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
