# Generated by Django 3.1 on 2022-01-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_auto_20220124_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobneed',
            name='ctzoffset',
            field=models.IntegerField(blank=True, null=True, verbose_name='TZ_Offset'),
        ),
    ]
