# Generated by Django 3.2.14 on 2022-12-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_alter_jobneed_deviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceeventlog',
            name='locationallowed',
            field=models.CharField(choices=[('locationalways', 'Location Always'), ('onlywhileyusing', 'Only While Using'), ('NONE', 'NONE')], default='NONE', max_length=25),
        ),
        migrations.AddField(
            model_name='deviceeventlog',
            name='locationserviceenabled',
            field=models.BooleanField(default=False, verbose_name='Is Location Serivice Enabled'),
        ),
        migrations.AlterField(
            model_name='deviceeventlog',
            name='eventvalue',
            field=models.CharField(choices=[('stepcount', 'Step Count'), ('locationalert', 'Location Alert'), ('devicelogs', 'Device Logs')], max_length=50, verbose_name='Device Event'),
        ),
        migrations.AlterField(
            model_name='deviceeventlog',
            name='networkprovidername',
            field=models.CharField(choices=[('bluetooth', 'Bluetooth'), ('wifi', 'WIFI'), ('ethernet', 'Ethernet'), ('mobile', 'Mobile'), ('none', 'None')], default='none', max_length=55),
        ),
    ]
