# Generated by Django 3.2.14 on 2022-12-28 10:07

import apps.activity.models
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0017_auto_20221227_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='geojson',
            field=models.JSONField(blank=True, default=apps.activity.models.geojson_jobnjobneed, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='geojson',
            field=models.JSONField(blank=True, default=apps.activity.models.geojson_jobnjobneed, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
