# Generated by Django 4.2 on 2024-06-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0017_alter_asset_cuser_alter_asset_muser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobneeddetails',
            name='answertype',
            field=models.CharField(choices=[('CHECKBOX', 'Checkbox'), ('DATE', 'Date'), ('DROPDOWN', 'Dropdown'), ('EMAILID', 'Email Id'), ('MULTILINE', 'Multiline'), ('NUMERIC', 'Numeric'), ('SIGNATURE', 'Signature'), ('SINGLELINE', 'Single Line'), ('TIME', 'Time'), ('RATING', 'Rating'), ('BACKCAMERA', 'Back Camera'), ('FRONTCAMERA', 'Front Camera'), ('PEOPLELIST', 'People List'), ('SITELIST', 'Site List'), ('NONE', 'NONE'), ('METERREADING', 'Meter Reading'), ('MULTISELECT', 'Multi Select')], max_length=50, null=True, verbose_name='Answer Type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answertype',
            field=models.CharField(choices=[('CHECKBOX', 'Checkbox'), ('DATE', 'Date'), ('DROPDOWN', 'Dropdown'), ('EMAILID', 'Email Id'), ('MULTILINE', 'Multiline'), ('NUMERIC', 'Numeric'), ('SIGNATURE', 'Signature'), ('SINGLELINE', 'Single Line'), ('TIME', 'Time'), ('RATING', 'Rating'), ('PEOPLELIST', 'People List'), ('SITELIST', 'Site List'), ('METERREADING', 'Meter Reading'), ('MULTISELECT', 'Multi Select')], default='NUMERIC', max_length=55, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='questionsetbelonging',
            name='answertype',
            field=models.CharField(choices=[('CHECKBOX', 'Checkbox'), ('DATE', 'Date'), ('DROPDOWN', 'Dropdown'), ('EMAILID', 'Email Id'), ('MULTILINE', 'Multiline'), ('NUMERIC', 'Numeric'), ('SIGNATURE', 'Signature'), ('SINGLELINE', 'Single Line'), ('TIME', 'Time'), ('RATING', 'Rating'), ('BACKCAMERA', 'Back Camera'), ('FRONTCAMERA', 'Front Camera'), ('PEOPLELIST', 'People List'), ('SITELIST', 'Site List'), ('NONE', 'NONE'), ('MULTISELECT', 'Multi Select')], max_length=50, verbose_name='Question Type'),
        ),
    ]
