# Generated by Django 4.2 on 2024-06-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0018_alter_jobneeddetails_answertype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsetbelonging',
            name='options',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Option'),
        ),
    ]
