# Generated by Django 3.2.14 on 2022-12-29 07:21

import apps.activity.models
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0018_auto_20221228_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='geojson',
            field=models.JSONField(blank=True, default=apps.activity.models.geojson_jobnjobneed, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='geojson',
            field=models.JSONField(blank=True, default=apps.activity.models.geojson_jobnjobneed, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
