# Generated by Django 3.2.14 on 2023-01-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0019_auto_20221229_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceeventlog',
            name='islocationmocked',
            field=models.BooleanField(default=False, verbose_name='Is Location Spoofed'),
        ),
    ]
