# Generated by Django 4.2 on 2024-06-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0019_alter_questionsetbelonging_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobneeddetails',
            name='options',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Option'),
        ),
    ]
