# Generated by Django 4.2 on 2024-07-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0020_alter_jobneeddetails_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='type',
            field=models.CharField(choices=[('CHECKLIST', 'Checklist'), ('RPCHECKLIST', 'RP Checklist'), ('INCIDENTREPORT', 'Incident Report'), ('SITEREPORT', 'Site Report'), ('WORKPERMIT', 'Work Permit'), ('RETURN_WORK_PERMIT', 'Return Work Permit'), ('KPITEMPLATE', 'Kpi'), ('SCRAPPEDTEMPLATE', 'Scrapped'), ('ASSETAUDIT', 'Asset Audit'), ('ASSETMAINTENANCE', 'Asset Maintenance'), ('WORK_ORDER', 'Work Order'), ('SLA_TEMPLATE', 'Service Level Agreement')], max_length=50, null=True, verbose_name='Type'),
        ),
    ]
