# Generated by Django 3.2.14 on 2023-01-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0020_deviceeventlog_islocationmocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceeventlog',
            old_name='androidversion',
            new_name='androidosversion',
        ),
    ]
