# Generated by Django 4.2 on 2024-11-19 09:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0021_alter_questionset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsetbelonging',
            name='buincludes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, null=True, size=None, verbose_name='Bu Includes'),
        ),
    ]
