# Generated by Django 3.2.14 on 2023-01-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0021_rename_androidversion_deviceeventlog_androidosversion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceeventlog',
            old_name='androidosversion',
            new_name='platformversion',
        ),
    ]
