# Generated by Django 4.2 on 2024-11-19 09:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0022_questionsetbelonging_buincludes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='assetincludes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None, verbose_name='Asset Includes'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='buincludes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None, verbose_name='Bu Includes'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='site_grp_includes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None, verbose_name='Site Group Includes'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='site_type_includes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None, verbose_name='Site Type Includes'),
        ),
        migrations.AlterField(
            model_name='questionsetbelonging',
            name='buincludes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None, verbose_name='Bu Includes'),
        ),
    ]
