# Generated by Django 3.2.14 on 2023-01-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0022_rename_androidosversion_deviceeventlog_platformversion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceeventlog',
            old_name='locationallowed',
            new_name='locationpermission',
        ),
    ]
