# Generated by Django 4.2 on 2024-11-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0023_alter_questionset_assetincludes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobname',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
