# Generated by Django 3.2.14 on 2023-01-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0023_rename_locationallowed_deviceeventlog_locationpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceeventlog',
            name='installedapps',
            field=models.CharField(default='NA', max_length=500, verbose_name='Installed Apps'),
        ),
    ]
