# Generated by Django 3.2.14 on 2023-01-11 03:21

import apps.activity.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0024_alter_deviceeventlog_installedapps'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='escalationmatrix',
            managers=[
                ('objects', apps.activity.managers.ESCManager()),
            ],
        ),
        migrations.AddField(
            model_name='escalationmatrix',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.job', verbose_name='Job'),
        ),
        migrations.AddField(
            model_name='escalationmatrix',
            name='type',
            field=models.CharField(choices=[('JOB', 'Job'), ('ESCALATION', 'Escalation')], max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='deviceeventlog',
            name='eventvalue',
            field=models.CharField(choices=[('stepcount', 'Step Count'), ('locationalert', 'Location Alert'), ('devicelogs', 'Device Logs'), ('login', 'Log In'), ('logout', 'Log Out')], max_length=50, verbose_name='Device Event'),
        ),
    ]
