# Generated by Django 4.2 on 2025-01-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0024_alter_job_jobname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobneed',
            name='identifier',
            field=models.CharField(choices=[('TASK', 'Task'), ('TICKET', 'Ticket'), ('INTERNALTOUR', 'Internal Tour'), ('EXTERNALTOUR', 'External Tour'), ('PPM', 'PPM'), ('OTHER', 'Other'), ('SITEREPORT', 'Site Report'), ('INCIDENTREPORT', 'Incident Report'), ('ASSETLOG', 'Asset Log'), ('ASSETAUDIT', 'Asset Audit'), ('ASSETMAINTENANCE', 'Asset Maintenance'), ('POSTING_ORDER', 'Posting Order')], max_length=50, null=True, verbose_name='Jobneed Type'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='type',
            field=models.CharField(choices=[('CHECKLIST', 'Checklist'), ('RPCHECKLIST', 'RP Checklist'), ('INCIDENTREPORT', 'Incident Report'), ('SITEREPORT', 'Site Report'), ('WORKPERMIT', 'Work Permit'), ('RETURN_WORK_PERMIT', 'Return Work Permit'), ('KPITEMPLATE', 'Kpi'), ('SCRAPPEDTEMPLATE', 'Scrapped'), ('ASSETAUDIT', 'Asset Audit'), ('ASSETMAINTENANCE', 'Asset Maintenance'), ('WORK_ORDER', 'Work Order'), ('SLA_TEMPLATE', 'Service Level Agreement'), ('POSTING_ORDER', 'Posting Order')], max_length=50, null=True, verbose_name='Type'),
        ),
    ]
