# Generated by Django 3.2.14 on 2023-01-11 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_auto_20221021_1344'),
        ('activity', '0025_auto_20230111_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalationmatrix',
            name='type',
        ),
        migrations.AddField(
            model_name='escalationmatrix',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='esc_clients', to='onboarding.bt'),
        ),
    ]
