# Generated by Django 4.2 on 2025-04-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0025_alter_jobneed_identifier_alter_questionset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobneeddetails',
            name='alerton',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Alert On'),
        ),
    ]
