# Generated by Django 3.2.14 on 2023-01-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0026_auto_20230111_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assetcode',
            field=models.CharField(max_length=50, unique=True, verbose_name='Asset Code'),
        ),
    ]
