# Generated by Django 3.2.14 on 2023-01-17 08:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0027_alter_asset_assetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True),
        ),
    ]
