# Generated by Django 3.2.14 on 2023-01-19 06:49

import apps.activity.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0029_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'get_latest_by': ['mdtz', 'cdtz'], 'ordering': ['mdtz']},
        ),
        migrations.AlterModelManagers(
            name='location',
            managers=[
                ('objects', apps.activity.managers.LocationManager()),
            ],
        ),
        migrations.AlterModelTable(
            name='location',
            table='location',
        ),
    ]
