# Generated by Django 3.2.14 on 2023-01-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0031_asset_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='identifier',
            field=models.CharField(choices=[('NONE', 'None'), ('ASSET', 'Asset'), ('CHECKPOINT', 'Checkpoint'), ('NEA', 'Non Engineering Asset')], default='NONE', max_length=55, verbose_name='Asset Identifier'),
        ),
        migrations.AlterField(
            model_name='job',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('LOW', 'Low'), ('MEDIUM', 'Medium')], max_length=100, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quesname',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='seqno',
            field=models.SmallIntegerField(default=1, verbose_name='Sl No.'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='type',
            field=models.CharField(choices=[('CHECKLIST', 'Checklist'), ('INCIDENTREPORTTEMPLATE', 'Incident Report Template'), ('SITEREPORTTEMPLATE', 'Site Report Template'), ('WORKPERMITTEMPLATE', 'Work Permit Template'), ('RETURNWORKPERMITTEMPLATE', 'Return Work Permit Template'), ('KPITEMPLATE', 'Kpi Template'), ('SCRAPPEDTEMPLATE', 'Scrapped Template'), ('ASSETAUDIT', 'Asset Audit'), ('MAINTENANCETEMPLATE', 'Maintenance Template'), ('ASSETMAINTENANCE', 'Asset Maintenance'), ('QUESTIONSET', 'Question Set')], max_length=50, null=True, verbose_name='Type'),
        ),
    ]
