# Generated by Django 3.2.14 on 2023-02-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0032_auto_20230124_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assignedtogroup',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assignedtopeople',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='bu',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='cuser',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='muser',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='performedby',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='EscalationMatrix',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
