# Generated by Django 3.2.14 on 2023-02-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0033_auto_20230203_1538'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='job',
            name='jobname_asset_qset_id_parent_identifier_uk',
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('jobname', 'asset', 'qset', 'parent', 'identifier', 'client'), name='jobname_asset_qset_id_parent_identifier_client_uk'),
        ),
    ]
