# Generated by Django 3.2.14 on 2023-03-06 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_auto_20230124_1619'),
        ('activity', '0035_attachment_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='ticketcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_tktcategories', to='onboarding.typeassist', verbose_name='Notify Category'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='ticketcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.typeassist', verbose_name='Notify Category'),
        ),
    ]
