# Generated by Django 3.2.14 on 2023-03-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0036_auto_20230306_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobneed',
            name='jobstatus',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('AUTOCLOSED', 'Auto Closed'), ('COMPLETED', 'Completed'), ('INPROGRESS', 'Inprogress'), ('PARTIALLYCOMPLETED', 'Partially Completed')], max_length=60, null=True, verbose_name='Job Status'),
        ),
    ]
