# Generated by Django 3.2.14 on 2023-03-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0037_alter_jobneed_jobstatus'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('assetcode', 'client'), name='assetcode_client_uk'),
        ),
    ]
