# Generated by Django 3.2.14 on 2023-03-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0038_asset_assetcode_client_uk'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('loccode', 'client'), name='loccode_client_uk'),
        ),
    ]
