# Generated by Django 3.2.14 on 2023-03-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0039_location_loccode_client_uk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='type',
            field=models.CharField(choices=[('CHECKLIST', 'Checklist'), ('INCIDENTREPORT', 'Incident Report'), ('SITEREPORT', 'Site Report'), ('WORKPERMIT', 'Work Permit'), ('RETURNWORKPERMIT', 'Return Work Permit'), ('KPI', 'Kpi'), ('SCRAPPED', 'Scrapped'), ('ASSETAUDIT', 'Asset Audit'), ('MAINTENANCE', 'Maintenance'), ('ASSETMAINTENANCE', 'Asset Maintenance'), ('QUESTIONSET', 'Question Set')], max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='url',
            field=models.CharField(blank=True, default='NONE', max_length=250, null=True, verbose_name='Url'),
        ),
    ]
