# Generated by Django 3.2.14 on 2023-03-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0042_alter_questionset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='type',
            field=models.CharField(choices=[('CHECKLIST', 'Checklist'), ('INCIDENTREPORT', 'Incident Report'), ('SITEREPORT', 'Site Report'), ('WORKPERMIT', 'Work Permit'), ('RETURN_WORK_PERMIT', 'Return Work Permit'), ('KPITEMPLATE', 'Kpi'), ('SCRAPPEDTEMPLATE', 'Scrapped'), ('ASSETAUDIT', 'Asset Audit'), ('MAINTENANCETEMPLATE', 'Maintenance'), ('ASSETMAINTENANCE', 'Asset Maintenance'), ('WORK_PERMIT', 'Work Permit'), ('WORK_ORDER', 'Work Order')], max_length=50, null=True, verbose_name='Type'),
        ),
    ]
