# Generated by Django 3.2.14 on 2023-03-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0044_alter_questionset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobneed',
            name='identifier',
            field=models.CharField(choices=[('TASK', 'Task'), ('TICKET', 'Ticket'), ('INTERNALTOUR', 'Internal Tour'), ('EXTERNALTOUR', 'External Tour'), ('PPM', 'PPM'), ('OTHER', 'Other'), ('SITEREPORT', 'Site Report'), ('INCIDENTREPORT', 'Incident Report'), ('ASSETLOG', 'Asset Log'), ('ASSETAUDIT', 'Asset Audit'), ('ASSETMAINTENANCE', 'Asset Maintenance')], max_length=50, null=True, verbose_name='Jobneed Type'),
        ),
    ]
