# Generated by Django 3.2.14 on 2023-03-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0045_alter_jobneed_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobneed',
            name='raisedby',
        ),
    ]
