# Generated by Django 3.2.14 on 2023-04-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0046_remove_jobneed_raisedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceeventlog',
            name='installedapps',
            field=models.CharField(default='NA', max_length=1000, verbose_name='Installed Apps'),
        ),
    ]
