# Generated by Django 3.2.14 on 2023-04-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0047_alter_deviceeventlog_installedapps'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='show_to_all_sites',
            field=models.BooleanField(default=False, verbose_name='Applicable to all sites'),
        ),
    ]
