# Generated by Django 3.2.18 on 2023-04-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0049_alter_questionset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answertype',
            field=models.CharField(choices=[('CHECKBOX', 'Checkbox'), ('DATE', 'Date'), ('DROPDOWN', 'Dropdown'), ('EMAILID', 'Email Id'), ('MULTILINE', 'Multiline'), ('NUMERIC', 'Numeric'), ('SIGNATURE', 'Signature'), ('SINGLELINE', 'Single Line'), ('TIME', 'Time'), ('RATING', 'Rating'), ('PEOPLELIST', 'People List'), ('SITELIST', 'Site List'), ('METERREADING', 'Meter Reading')], default='NUMERIC', max_length=55, verbose_name='Type'),
        ),
    ]
