# Generated by Django 3.2.18 on 2023-04-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0050_alter_question_answertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobneeddetails',
            name='answertype',
            field=models.CharField(choices=[('CHECKBOX', 'Checkbox'), ('DATE', 'Date'), ('DROPDOWN', 'Dropdown'), ('EMAILID', 'Email Id'), ('MULTILINE', 'Multiline'), ('NUMERIC', 'Numeric'), ('SIGNATURE', 'Signature'), ('SINGLELINE', 'Single Line'), ('TIME', 'Time'), ('RATING', 'Rating'), ('BACKCAMERA', 'Back Camera'), ('FRONTCAMERA', 'Front Camera'), ('PEOPLELIST', 'People List'), ('SITELIST', 'Site List'), ('NONE', 'NONE'), ('METERREADING', 'Meter Reading')], max_length=50, null=True, verbose_name='Answer Type'),
        ),
    ]
