# Generated by Django 3.2.18 on 2023-05-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0051_alter_jobneeddetails_answertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachmenttype',
            field=models.CharField(choices=[('NONE', 'NONE'), ('ATTACHMENT', 'Attachment'), ('REPLY', 'Reply'), ('SIGN', 'SIGN'), ('METERREADING', 'Meter Reading'), ('LOGFILES', 'Log Files')], default='NONE', max_length=55),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='jobstatus',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('AUTOCLOSED', 'Auto Closed'), ('COMPLETED', 'Completed'), ('INPROGRESS', 'Inprogress'), ('PARTIALLYCOMPLETED', 'Partially Completed'), ('MAINTENANCE', 'Maintenance'), ('STANDBY', 'Standby'), ('WORKING', 'Working')], max_length=60, null=True, verbose_name='Job Status'),
        ),
    ]
