# Generated by Django 3.2.18 on 2023-05-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0052_auto_20230506_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='iscritical',
            field=models.BooleanField(verbose_name='Critical'),
        ),
        migrations.AlterField(
            model_name='deviceeventlog',
            name='islocationmocked',
            field=models.BooleanField(default=False, verbose_name='Location Spoofed'),
        ),
        migrations.AlterField(
            model_name='deviceeventlog',
            name='locationserviceenabled',
            field=models.BooleanField(default=False, verbose_name='Location Serivice Enabled'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='ismailsent',
            field=models.BooleanField(default=False, verbose_name='Mail Sent'),
        ),
        migrations.AlterField(
            model_name='jobneeddetails',
            name='isavpt',
            field=models.BooleanField(default=False, verbose_name='Attachement Required'),
        ),
        migrations.AlterField(
            model_name='jobneeddetails',
            name='ismandatory',
            field=models.BooleanField(default=True, verbose_name='Mandatory'),
        ),
        migrations.AlterField(
            model_name='location',
            name='iscritical',
            field=models.BooleanField(verbose_name='Critical'),
        ),
        migrations.AlterField(
            model_name='question',
            name='isavpt',
            field=models.BooleanField(default=False, verbose_name='Attachment Required'),
        ),
        migrations.AlterField(
            model_name='question',
            name='isworkflow',
            field=models.BooleanField(default=False, verbose_name='WorkFlow'),
        ),
        migrations.AlterField(
            model_name='questionsetbelonging',
            name='isavpt',
            field=models.BooleanField(default=False, verbose_name='Attachment Required'),
        ),
        migrations.AlterField(
            model_name='questionsetbelonging',
            name='ismandatory',
            field=models.BooleanField(verbose_name='Manadatory'),
        ),
    ]
