# Generated by Django 3.2.18 on 2023-05-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0053_auto_20230512_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='runningstatus',
            field=models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('STANDBY', 'Standby'), ('WORKING', 'Working'), ('SCRAPPED', 'Scrapped')], max_length=55, null=True, verbose_name='Running Status'),
        ),
    ]
