# Generated by Django 3.2.18 on 2023-05-25 10:16

import apps.activity.models
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0054_alter_asset_runningstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='other_info',
            field=models.JSONField(blank=True, default=apps.activity.models.other_info, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Other info'),
        ),
    ]
