# Generated by Django 3.2.18 on 2023-05-29 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0055_alter_job_other_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobneeddetails',
            name='qset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='questions_qset', to='activity.questionset', verbose_name='Question Set'),
        ),
    ]
