# Generated by Django 3.2.18 on 2023-05-30 11:30

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0010_auto_20230512_0128'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0056_jobneeddetails_qset'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, unique=True)),
                ('oldstatus', models.CharField(max_length=50, verbose_name='Old Status')),
                ('newstatus', models.CharField(max_length=50, verbose_name='New Status')),
                ('cdtz', models.DateTimeField(null=True, verbose_name='Created On')),
                ('gpslocation', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='GPS Location')),
                ('ctzoffset', models.IntegerField(default=-1, verbose_name='TimeZone')),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.asset', verbose_name='Asset')),
                ('bu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt', verbose_name='Bu')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assetlog_client', to='onboarding.bt', verbose_name='Client')),
                ('people', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='People')),
            ],
        ),
    ]
