# Generated by Django 3.2.18 on 2023-05-31 05:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0057_assetlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlog',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
