# Generated by Django 3.2.18 on 2023-05-31 05:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0058_alter_assetlog_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlog',
            name='oldstatus',
            field=models.CharField(max_length=50, null=True, verbose_name='Old Status'),
        ),
        migrations.AlterField(
            model_name='assetlog',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True),
        ),
    ]
