# Generated by Django 3.2.18 on 2023-05-31 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0059_auto_20230531_0037'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assetlog',
            table='assetlog',
        ),
    ]
