# Generated by Django 3.2.18 on 2023-06-01 06:39

import apps.activity.models
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('y_helpdesk', '0014_ticket_identifier'),
        ('activity', '0060_alter_assetlog_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobneed',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneed_ticket', to='y_helpdesk.ticket', verbose_name='Ticket'),
        ),
        migrations.AlterField(
            model_name='job',
            name='other_info',
            field=models.JSONField(blank=True, default=apps.activity.models.other_info, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Other info'),
        ),
    ]
