# Generated by Django 3.2.18 on 2023-06-14 08:05

import apps.activity.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0061_auto_20230601_0139'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='assetlog',
            managers=[
                ('objects', apps.activity.managers.AssetLogManager()),
            ],
        ),
        migrations.AlterField(
            model_name='questionset',
            name='type',
            field=models.CharField(choices=[('CHECKLIST', 'Checklist'), ('RPCHECKLIST', 'RP Checklist'), ('INCIDENTREPORT', 'Incident Report'), ('SITEREPORT', 'Site Report'), ('WORKPERMIT', 'Work Permit'), ('RETURN_WORK_PERMIT', 'Return Work Permit'), ('KPITEMPLATE', 'Kpi'), ('SCRAPPEDTEMPLATE', 'Scrapped'), ('ASSETAUDIT', 'Asset Audit'), ('ASSETMAINTENANCE', 'Asset Maintenance'), ('WORK_ORDER', 'Work Order')], max_length=50, null=True, verbose_name='Type'),
        ),
    ]
