# Generated by Django 3.2.18 on 2023-06-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0062_auto_20230614_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quesname',
            field=models.CharField(max_length=500, verbose_name='Name'),
        ),
    ]
