# Generated by Django 3.2.4 on 2021-07-10 06:22

import apps.onboarding.models
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bt',
            fields=[
                ('cdtz', models.DateTimeField(auto_now_add=True, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(auto_now=True, verbose_name='mdtz')),
                ('btid', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='btid')),
                ('bucode', models.CharField(max_length=15, verbose_name='bucode')),
                ('bu_preferences', models.JSONField(blank=True, default=apps.onboarding.models.bu_defaults, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='bu_preferences')),
                ('buname', models.CharField(max_length=200, verbose_name='buname')),
                ('enable', models.BooleanField(default=True, verbose_name='enable')),
                ('iswarehouse', models.BooleanField(default=False, verbose_name='iswarehouse')),
                ('gpsenable', models.BooleanField(default=False, verbose_name='gpsenable')),
                ('enablesleepingguard', models.BooleanField(default=False, verbose_name='enablesleepingguard')),
                ('skipsiteaudit', models.BooleanField(default=False, verbose_name='skipsiteaudit')),
                ('siincludes', models.TextField(default='', verbose_name='siincludes')),
                ('deviceevent', models.BooleanField(default=False, verbose_name='deviceevent')),
                ('pdist', models.FloatField(blank=True, default=0.0, null=True, verbose_name='pdist')),
                ('gpslocation', models.CharField(max_length=50, verbose_name='gpslocation')),
            ],
            options={
                'verbose_name': 'Buisiness Unit',
                'verbose_name_plural': 'Buisiness Units',
                'db_table': 'bt',
                'ordering': ['mdtz'],
                'get_latest_by': ['mdtz', 'cdtz'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeAssist',
            fields=[
                ('cdtz', models.DateTimeField(auto_now_add=True, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(auto_now=True, verbose_name='mdtz')),
                ('tacode', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='tacode')),
                ('taname', models.CharField(max_length=100, verbose_name='taname')),
                ('tatype', models.CharField(max_length=100, verbose_name='tatype')),
                ('buid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ta_buids', to='onboarding.bt')),
            ],
            options={
                'db_table': 'typeassist',
                'ordering': ['mdtz'],
                'abstract': False,
            },
        ),
    ]
