# Generated by Django 3.1 on 2021-10-13 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='typeassist',
            name='cuser',
            field=models.ForeignKey(blank=True, db_column='cuser', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='typeassist_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typeassist',
            name='muser',
            field=models.ForeignKey(blank=True, db_column='muser', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='typeassist_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typeassist',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='onboarding.typeassist'),
        ),
        migrations.AddField(
            model_name='typeassist',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='sitepeople',
            name='buid',
            field=models.ForeignKey(db_column='buid', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_buid', to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='sitepeople',
            name='contract_id',
            field=models.ForeignKey(db_column='contract', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_contractid', to='onboarding.contract'),
        ),
        migrations.AddField(
            model_name='sitepeople',
            name='contractdetailid',
            field=models.ForeignKey(db_column='contractdetailid', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_contractdetail', to='onboarding.contractdetail'),
        ),
        migrations.AddField(
            model_name='sitepeople',
            name='cuser',
            field=models.ForeignKey(blank=True, db_column='cuser', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sitepeople_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitepeople',
            name='muser',
            field=models.ForeignKey(blank=True, db_column='muser', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sitepeople_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitepeople',
            name='peopleid',
            field=models.ForeignKey(db_column='peopleid', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitepeople',
            name='reportto',
            field=models.ForeignKey(db_column='reportto', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_reportto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitepeople',
            name='shift',
            field=models.ForeignKey(db_column='shift', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_shift', to='onboarding.shift'),
        ),
        migrations.AddField(
            model_name='sitepeople',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='sitepeople',
            name='worktype',
            field=models.ForeignKey(db_column='worktype', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_worktype', to='onboarding.typeassist'),
        ),
        migrations.AddField(
            model_name='shift',
            name='buid',
            field=models.ForeignKey(db_column='buid', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shift_buid', to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='shift',
            name='cuser',
            field=models.ForeignKey(blank=True, db_column='cuser', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shift_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='muser',
            field=models.ForeignKey(blank=True, db_column='muser', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shift_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='contractdetail',
            name='contractid',
            field=models.ForeignKey(db_column='contractid', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cd_contract', to='onboarding.contract'),
        ),
        migrations.AddField(
            model_name='contractdetail',
            name='cuser',
            field=models.ForeignKey(blank=True, db_column='cuser', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contractdetail_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractdetail',
            name='muser',
            field=models.ForeignKey(blank=True, db_column='muser', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contractdetail_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractdetail',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='contractdetail',
            name='worktype',
            field=models.ForeignKey(db_column='worktype', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cd_worktype', to='onboarding.typeassist'),
        ),
        migrations.AddField(
            model_name='contract',
            name='buid',
            field=models.ForeignKey(db_column='buid', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contract_buid', to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='contract',
            name='cuser',
            field=models.ForeignKey(blank=True, db_column='cuser', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contract_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='customerid',
            field=models.ForeignKey(db_column='customerid', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contract_customer', to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='contract',
            name='muser',
            field=models.ForeignKey(blank=True, db_column='muser', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contract_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='bt',
            name='butype',
            field=models.ForeignKey(blank=True, db_column='butype', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bu_butypes', to='onboarding.typeassist'),
        ),
        migrations.AddField(
            model_name='bt',
            name='cuser',
            field=models.ForeignKey(blank=True, db_column='cuser', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bt_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bt',
            name='identifier',
            field=models.ForeignKey(blank=True, db_column='identifier', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bu_idfs', to='onboarding.typeassist'),
        ),
        migrations.AddField(
            model_name='bt',
            name='muser',
            field=models.ForeignKey(blank=True, db_column='muser', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bt_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bt',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='bt',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='typeassist',
            constraint=models.UniqueConstraint(fields=('tacode',), name='ta_tacode_uk'),
        ),
        migrations.AddConstraint(
            model_name='sitepeople',
            constraint=models.UniqueConstraint(fields=('peopleid', 'buid', 'posting_revision', 'contract_id', 'slno'), name='people_buid_postrev_contr_slno_uk'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('shiftname', 'buid'), name='shiftname_buid_uk'),
        ),
        migrations.AddConstraint(
            model_name='contractdetail',
            constraint=models.CheckConstraint(check=models.Q(quantity__gte=0), name='qty_gte_0_ck'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('contractname', 'revno', 'buid'), name='cname_revno_buid_uk'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(check=models.Q(revno__gte=0), name='revno_gte_0_ck'),
        ),
        migrations.AddConstraint(
            model_name='bt',
            constraint=models.UniqueConstraint(fields=('bucode', 'parent', 'identifier'), name='bu_bucode_parent_identifier_uk'),
        ),
    ]
