# Generated by Django 3.2.4 on 2021-07-10 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeassist',
            name='cuser',
            field=models.ForeignKey(blank=True, db_column='cuser', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='typeassist_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typeassist',
            name='muser',
            field=models.ForeignKey(blank=True, db_column='muser', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='typeassist_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typeassist',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ta_parents', to='onboarding.typeassist'),
        ),
        migrations.AddField(
            model_name='typeassist',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='bt',
            name='butype',
            field=models.ForeignKey(blank=True, db_column='butype', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bu_butypes', to='onboarding.typeassist'),
        ),
        migrations.AddField(
            model_name='bt',
            name='cuser',
            field=models.ForeignKey(blank=True, db_column='cuser', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bt_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bt',
            name='identifier',
            field=models.ForeignKey(blank=True, db_column='identifier', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bu_idfs', to='onboarding.typeassist'),
        ),
        migrations.AddField(
            model_name='bt',
            name='muser',
            field=models.ForeignKey(blank=True, db_column='muser', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bt_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bt',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bu_parent', to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='bt',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='typeassist',
            constraint=models.UniqueConstraint(fields=('tacode',), name='ta_tacode_uk'),
        ),
        migrations.AddConstraint(
            model_name='bt',
            constraint=models.UniqueConstraint(fields=('bucode', 'parent', 'identifier'), name='bu_bucode_parent_identifier_uk'),
        ),
    ]
