# Generated by Django 3.2 on 2022-03-30 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
        ('onboarding', '0001_initial'),
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizarddraft',
            name='createdby',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typeassist',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ta_bus', to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='typeassist',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='typeassist_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typeassist',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='typeassist_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typeassist',
            name='tatype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='onboarding.typeassist'),
        ),
        migrations.AddField(
            model_name='typeassist',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='sitepeople',
            name='bu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_bu', to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='sitepeople',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_contract', to='onboarding.contract'),
        ),
        migrations.AddField(
            model_name='sitepeople',
            name='contractdetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_contractdetail', to='onboarding.contractdetail'),
        ),
        migrations.AddField(
            model_name='sitepeople',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sitepeople_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitepeople',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sitepeople_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitepeople',
            name='people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitepeople',
            name='reportto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_reportto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitepeople',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_shift', to='onboarding.shift'),
        ),
        migrations.AddField(
            model_name='sitepeople',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='sitepeople',
            name='worktype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_worktype', to='onboarding.typeassist'),
        ),
        migrations.AddField(
            model_name='shift',
            name='bu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shift_bu', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='shift',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shift_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shift_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='geofencemaster',
            name='alerttogroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='peoples.pgroup', verbose_name='Alert to Group'),
        ),
        migrations.AddField(
            model_name='geofencemaster',
            name='alerttopeople',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AddField(
            model_name='geofencemaster',
            name='bu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='for_sites', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='geofencemaster',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='for_clients', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='geofencemaster',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='geofencemaster_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geofencemaster',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='geofencemaster_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractdetail',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cd_contract', to='onboarding.contract', verbose_name='Contract'),
        ),
        migrations.AddField(
            model_name='contractdetail',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contractdetail_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractdetail',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contractdetail_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractdetail',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='contractdetail',
            name='worktype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cd_worktype', to='onboarding.typeassist', verbose_name='Work Type'),
        ),
        migrations.AddField(
            model_name='contract',
            name='bu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contract_bu', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='contract',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contract_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contract_customer', to='onboarding.bt', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contract_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='bt',
            name='butype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bu_butypes', to='onboarding.typeassist', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='bt',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bt_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bt',
            name='identifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bu_idfs', to='onboarding.typeassist', verbose_name='Identifier'),
        ),
        migrations.AddField(
            model_name='bt',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bt_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bt',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='onboarding.bt', verbose_name='Belongs To'),
        ),
        migrations.AddField(
            model_name='bt',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='wizarddraft',
            constraint=models.UniqueConstraint(fields=('createdby', 'id'), name='draft_per_user'),
        ),
        migrations.AddConstraint(
            model_name='sitepeople',
            constraint=models.UniqueConstraint(fields=('people', 'bu', 'posting_revision', 'contract', 'slno'), name='people_bu_postrev_contr_slno_uk'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('shiftname', 'bu'), name='shiftname_bu_uk'),
        ),
        migrations.AddConstraint(
            model_name='geofencemaster',
            constraint=models.UniqueConstraint(fields=('gfcode', 'bu'), name='gfcode_bu_uk'),
        ),
        migrations.AddConstraint(
            model_name='contractdetail',
            constraint=models.CheckConstraint(check=models.Q(quantity__gte=0), name='qty_gte_0_ck'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('contractname', 'revno', 'bu'), name='cname_revno_bu_uk'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(check=models.Q(revno__gte=0), name='revno_gte_0_ck'),
        ),
        migrations.AddConstraint(
            model_name='bt',
            constraint=models.UniqueConstraint(fields=('bucode', 'parent', 'identifier'), name='bu_bucode_parent_identifier_uk'),
        ),
    ]
