# Generated by Django 3.1 on 2022-02-11 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_auto_20220201_1540'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contract',
            name='cname_revno_buid_uk',
        ),
        migrations.RemoveConstraint(
            model_name='geofencemaster',
            name='gfcode_buid_uk',
        ),
        migrations.RemoveConstraint(
            model_name='shift',
            name='shiftname_buid_uk',
        ),
        migrations.RemoveConstraint(
            model_name='sitepeople',
            name='people_buid_postrev_contr_slno_uk',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='customerid',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='contractdetail',
            old_name='contractid',
            new_name='contract',
        ),
        migrations.RenameField(
            model_name='geofencemaster',
            old_name='buid',
            new_name='bu',
        ),
        migrations.RenameField(
            model_name='geofencemaster',
            old_name='clientid',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='sitepeople',
            old_name='contractdetailid',
            new_name='contractdetail',
        ),
        migrations.RenameField(
            model_name='sitepeople',
            old_name='peopleid',
            new_name='people',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='buid',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='buid',
        ),
        migrations.RemoveField(
            model_name='sitepeople',
            name='buid',
        ),
        migrations.RemoveField(
            model_name='sitepeople',
            name='contract_id',
        ),
        migrations.RemoveField(
            model_name='typeassist',
            name='buid',
        ),
        migrations.RemoveField(
            model_name='wizarddraft',
            name='buid',
        ),
        migrations.AddField(
            model_name='contract',
            name='bu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contract_bu', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='shift',
            name='bu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shift_bu', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='sitepeople',
            name='bu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_bu', to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='sitepeople',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_contract', to='onboarding.contract'),
        ),
        migrations.AddField(
            model_name='typeassist',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ta_bus', to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='wizarddraft',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiz_bus', to='onboarding.bt'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('contractname', 'revno', 'bu'), name='cname_revno_bu_uk'),
        ),
        migrations.AddConstraint(
            model_name='geofencemaster',
            constraint=models.UniqueConstraint(fields=('gfcode', 'bu'), name='gfcode_bu_uk'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('shiftname', 'bu'), name='shiftname_bu_uk'),
        ),
        migrations.AddConstraint(
            model_name='sitepeople',
            constraint=models.UniqueConstraint(fields=('people', 'bu', 'posting_revision', 'contract', 'slno'), name='people_bu_postrev_contr_slno_uk'),
        ),
    ]
