# Generated by Django 3.2.18 on 2023-07-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='typeassist',
            name='code_unique2',
        ),
    ]
