# Generated by Django 3.2 on 2022-03-19 12:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofencemaster',
            name='geofence',
            field=django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326, verbose_name='GeoFence'),
        ),
    ]
