# Generated by Django 3.2.14 on 2022-10-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeassist',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Enable'),
        ),
    ]
