# Generated by Django 3.2 on 2022-04-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bt',
            name='bucode',
            field=models.CharField(max_length=30, verbose_name='Code'),
        ),
    ]
