# Generated by Django 3.2 on 2022-03-30 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeassist',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ta_clients', to='onboarding.bt'),
        ),
        migrations.AlterModelTable(
            name='wizarddraft',
            table='wizarddraft',
        ),
    ]
