# Generated by Django 3.2.4 on 2021-08-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bt',
            name='btid',
            field=models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='btid'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractid',
            field=models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contractdetail',
            name='contractdetailid',
            field=models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shiftid',
            field=models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sitepeople',
            name='sitepeopleid',
            field=models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='typeassist',
            name='taid',
            field=models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
