# Generated by Django 3.2 on 2022-05-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sitepeople',
            name='people_bu_postrev_contr_slno_uk',
        ),
        migrations.RenameField(
            model_name='sitepeople',
            old_name='slno',
            new_name='seqno',
        ),
        migrations.AddConstraint(
            model_name='sitepeople',
            constraint=models.UniqueConstraint(fields=('people', 'bu', 'posting_revision', 'contract', 'seqno'), name='people_bu_postrev_contr_slno_uk'),
        ),
    ]
