# Generated by Django 3.1 on 2021-10-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_auto_20211013_1449'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='typeassist',
            name='ta_tacode_uk',
        ),
        migrations.AlterField(
            model_name='typeassist',
            name='tacode',
            field=models.CharField(max_length=50, unique=True, verbose_name='tacode'),
        ),
    ]
