# Generated by Django 3.2.14 on 2022-10-21 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0003_typeassist_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='bt',
            name='siteincharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='siteincharge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bt',
            name='solid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
