# Generated by Django 3.2 on 2022-04-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_alter_bt_bucode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bt',
            old_name='tzoffset',
            new_name='ctzoffset',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='tzoffset',
            new_name='ctzoffset',
        ),
        migrations.RenameField(
            model_name='contractdetail',
            old_name='tzoffset',
            new_name='ctzoffset',
        ),
        migrations.RenameField(
            model_name='geofencemaster',
            old_name='tzoffset',
            new_name='ctzoffset',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='tzoffset',
            new_name='ctzoffset',
        ),
        migrations.RenameField(
            model_name='sitepeople',
            old_name='tzoffset',
            new_name='ctzoffset',
        ),
        migrations.RenameField(
            model_name='typeassist',
            old_name='tzoffset',
            new_name='ctzoffset',
        ),
    ]
