# Generated by Django 3.1 on 2022-01-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_auto_20220118_1723'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='geofencemaster',
            name='gfcode_siteid_uk',
        ),
        migrations.RenameField(
            model_name='geofencemaster',
            old_name='siteid',
            new_name='buid',
        ),
        migrations.AddConstraint(
            model_name='geofencemaster',
            constraint=models.UniqueConstraint(fields=('gfcode', 'buid'), name='gfcode_buid_uk'),
        ),
    ]
