# Generated by Django 3.1 on 2022-02-28 07:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_auto_20220211_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bt',
            name='gpslocation',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='GPS Location'),
        ),
    ]
