# Generated by Django 3.2 on 2022-06-07 05:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_auto_20220503_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bt',
            name='siincludes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, null=True, size=None, verbose_name='Site Inclides'),
        ),
    ]
