# Generated by Django 3.2.18 on 2023-12-06 09:12

import apps.peoples.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from datetime import timezone

utc = timezone.utc

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0003_remove_typeassist_code_unique2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownTimeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='mdtz')),
                ('ctzoffset', models.IntegerField(default=-1, verbose_name='TimeZone')),
                ('reason', models.TextField(verbose_name='Downtime Reason')),
                ('starttime', models.DateTimeField(default=datetime.datetime(2023, 12, 6, 9, 12, 53, 561160, tzinfo=utc), verbose_name='Start')),
                ('endtime', models.DateTimeField(default=datetime.datetime(2023, 12, 6, 9, 12, 53, 561182, tzinfo=utc), verbose_name='End')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='downtimehistory_cusers', to=settings.AUTH_USER_MODEL)),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='downtimehistory_musers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'downtime_history',
                'ordering': ['mdtz'],
                'get_latest_by': ['mdtz'],
                'abstract': False,
            },
        ),
    ]
