# Generated by Django 3.1 on 2021-10-19 05:39

import apps.onboarding.models
from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0003_auto_20211013_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='WizardDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(auto_now_add=True)),
                ('mdtz', models.DateTimeField(auto_now=True)),
                ('wizard_data', models.JSONField(blank=True, default=apps.onboarding.models.wizard_default, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('form_data', models.JSONField(blank=True, default=apps.onboarding.models.formData_default, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('buid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiz_buids', to='onboarding.bt')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wizard_draft',
                'get_latest_by': ['mdtz'],
            },
        ),
        migrations.AddConstraint(
            model_name='wizarddraft',
            constraint=models.UniqueConstraint(fields=('createdby', 'id'), name='draft_per_user'),
        ),
    ]
