# Generated by Django 3.1 on 2022-02-01 05:37

import apps.onboarding.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_auto_20220122_1132'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bt',
            managers=[
                ('objects', apps.onboarding.managers.BtManager()),
            ],
        ),
    ]
