# Generated by Django 3.1 on 2022-02-28 13:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_auto_20220228_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofencemaster',
            name='geofence',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='GeoFence'),
        ),
    ]
