# Generated by Django 3.2.14 on 2022-10-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_auto_20221021_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeassist',
            name='tacode',
            field=models.CharField(max_length=50, verbose_name='tacode'),
        ),
        migrations.AddConstraint(
            model_name='typeassist',
            constraint=models.UniqueConstraint(fields=('tacode', 'tatype'), name='code_unique'),
        ),
        migrations.AddConstraint(
            model_name='typeassist',
            constraint=models.UniqueConstraint(condition=models.Q(('tatype', None)), fields=('tacode',), name='code_unique2'),
        ),
    ]
