# Generated by Django 3.2.18 on 2023-12-06 09:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_downtimehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtimehistory',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='downtimehistory',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 9, 46, 2, 76608, tzinfo=utc), verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='downtimehistory',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 9, 46, 2, 76585, tzinfo=utc), verbose_name='Start'),
        ),
    ]
