# Generated by Django 3.2.18 on 2023-12-07 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_auto_20231206_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtimehistory',
            name='endtime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='downtimehistory',
            name='starttime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start'),
        ),
    ]
