# Generated by Django 3.2.14 on 2023-01-24 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0005_auto_20221021_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bt',
            name='pdist',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Permissible Distance'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='siteincharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='siteincharge', to=settings.AUTH_USER_MODEL, verbose_name='Site Incharge'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='solid',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Sol ID'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='bu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shift_bu', to='onboarding.bt', verbose_name='Buisiness View'),
        ),
        migrations.AlterField(
            model_name='typeassist',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ta_bus', to='onboarding.bt', verbose_name='Buisiness View'),
        ),
        migrations.AlterField(
            model_name='typeassist',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ta_clients', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='typeassist',
            name='tatype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='onboarding.typeassist', verbose_name='TypeAssist'),
        ),
    ]
