# Generated by Django 3.1 on 2021-11-08 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_auto_20211108_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bt',
            name='bucode',
            field=models.CharField(max_length=15, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='buname',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='butype',
            field=models.ForeignKey(blank=True, db_column='butype', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bu_butypes', to='onboarding.typeassist', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='onboarding.bt', verbose_name='Belongs To'),
        ),
    ]
