# Generated by Django 3.2.14 on 2023-03-06 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_auto_20230124_1619'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shift',
            name='shiftname_bu_uk',
        ),
        migrations.AddField(
            model_name='shift',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shift_client', to='onboarding.bt', verbose_name='Buisiness View'),
        ),
        migrations.AddField(
            model_name='shift',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.typeassist', verbose_name='Buisiness View'),
        ),
        migrations.AddField(
            model_name='shift',
            name='peoplecount',
            field=models.IntegerField(blank=True, null=True, verbose_name='People Count'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('shiftname', 'bu', 'designation', 'client'), name='shiftname_bu_desgn_client_uk'),
        ),
    ]
