# Generated by Django 3.2.18 on 2024-02-01 05:47

import apps.peoples.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
        ('onboarding', '0006_auto_20231207_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='mdtz')),
                ('ctzoffset', models.IntegerField(default=-1, verbose_name='TimeZone')),
                ('handsetname', models.CharField(max_length=100, verbose_name='Handset Name')),
                ('modelname', models.CharField(max_length=50, verbose_name='Model')),
                ('dateregistered', models.DateField(default=django.utils.timezone.now, verbose_name='Date Registered')),
                ('lastcommunication', models.DateTimeField(verbose_name='Last Communication')),
                ('imeino', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='IMEI No')),
                ('phoneno', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone No')),
                ('isdeviceon', models.BooleanField(default=True, verbose_name='Is Device On')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt', verbose_name='Client')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='device_cusers', to=settings.AUTH_USER_MODEL)),
                ('lastloggedinuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Last Logged In User')),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='device_musers', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'device',
                'ordering': ['mdtz'],
                'get_latest_by': ['mdtz', 'cdtz'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='mdtz')),
                ('ctzoffset', models.IntegerField(default=-1, verbose_name='TimeZone')),
                ('startdate', models.DateField(verbose_name='Start Date')),
                ('enddate', models.DateField(verbose_name='End Date')),
                ('terminateddate', models.DateField(verbose_name='Terminated Date')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], default='Active', max_length=50, verbose_name='Status')),
                ('assignedhandset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.device', verbose_name='Assigned Handset')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt', verbose_name='Client')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='subscription_cusers', to=settings.AUTH_USER_MODEL)),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='subscription_musers', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['mdtz'],
                'abstract': False,
            },
        ),
    ]
