# Generated by Django 3.1 on 2021-11-15 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_auto_20211108_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='buid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shift_buid', to='onboarding.bt'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='endtime',
            field=models.TimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='nightshift_appicable',
            field=models.BooleanField(default=True, verbose_name='Night Shift Applicable'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shiftduration',
            field=models.IntegerField(null=True, verbose_name='Shift Duration'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shiftname',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='starttime',
            field=models.TimeField(verbose_name='Start time'),
        ),
    ]
