# Generated by Django 3.2.18 on 2024-02-07 06:57

import apps.onboarding.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_device_subscription'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='device',
            managers=[
                ('objects', apps.onboarding.managers.DeviceManager()),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='istemporary',
            field=models.BooleanField(default=False, verbose_name='Is Temporary'),
        ),
    ]
