# Generated by Django 3.2.14 on 2023-03-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_auto_20230306_1628'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='typeassist',
            name='code_unique',
        ),
        migrations.RemoveConstraint(
            model_name='typeassist',
            name='code_unique2',
        ),
        migrations.AddConstraint(
            model_name='typeassist',
            constraint=models.UniqueConstraint(fields=('tacode', 'tatype', 'client'), name='code_unique'),
        ),
        migrations.AddConstraint(
            model_name='typeassist',
            constraint=models.UniqueConstraint(condition=models.Q(('tatype', None)), fields=('tacode', 'client'), name='code_unique2'),
        ),
    ]
