# Generated by Django 3.2.14 on 2023-03-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0008_auto_20230313_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='bt',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
    ]
