# Generated by Django 3.2.18 on 2024-02-08 08:06

import apps.onboarding.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0008_auto_20240207_0657'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subscription',
            managers=[
                ('objects', apps.onboarding.managers.SubscriptionManger()),
            ],
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('startdate', 'enddate', 'client'), name='startdate_enddate_client_uk'),
        ),
        migrations.AlterModelTable(
            name='subscription',
            table='subscription',
        ),
    ]
