# Generated by Django 3.1 on 2021-11-15 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0008_auto_20211115_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bt',
            name='butree',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Bu Path'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='butype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bu_butypes', to='onboarding.typeassist', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bt_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bt',
            name='deviceevent',
            field=models.BooleanField(default=False, verbose_name='Device Event'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Enable'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='enablesleepingguard',
            field=models.BooleanField(default=False, verbose_name='Enable SleepingGuard'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='gpsenable',
            field=models.BooleanField(default=False, verbose_name='GPS Enable'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='gpslocation',
            field=models.CharField(blank=True, default='0.0,0.0', max_length=50, null=True, verbose_name='GPS Location'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='identifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bu_idfs', to='onboarding.typeassist', verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='is_serviceprovider',
            field=models.BooleanField(default=False, verbose_name='Is ServiceProvider'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='isvendor',
            field=models.BooleanField(default=False, verbose_name='Is Vendor'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='iswarehouse',
            field=models.BooleanField(default=False, verbose_name='Is Warehouse'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bt_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bt',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='onboarding.bt', verbose_name='Belongs To'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='siincludes',
            field=models.TextField(default='', verbose_name='Site Inclides'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='skipsiteaudit',
            field=models.BooleanField(default=False, verbose_name='Skip SiteAudit'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='buid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contract_buid', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contract_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customerid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contract_customer', to='onboarding.bt', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contract_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractdetail',
            name='contractid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cd_contract', to='onboarding.contract', verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='contractdetail',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contractdetail_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractdetail',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contractdetail_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractdetail',
            name='worktype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cd_worktype', to='onboarding.typeassist', verbose_name='Work Type'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='buid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shift_buid', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shift_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shift',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shift_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitepeople',
            name='buid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_buid', to='onboarding.bt'),
        ),
        migrations.AlterField(
            model_name='sitepeople',
            name='contract_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_contractid', to='onboarding.contract'),
        ),
        migrations.AlterField(
            model_name='sitepeople',
            name='contractdetailid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_contractdetail', to='onboarding.contractdetail'),
        ),
        migrations.AlterField(
            model_name='sitepeople',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sitepeople_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitepeople',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sitepeople_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitepeople',
            name='peopleid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitepeople',
            name='reportto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_reportto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitepeople',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_shift', to='onboarding.shift'),
        ),
        migrations.AlterField(
            model_name='sitepeople',
            name='worktype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sp_worktype', to='onboarding.typeassist'),
        ),
        migrations.AlterField(
            model_name='typeassist',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='typeassist_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='typeassist',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='typeassist_musers', to=settings.AUTH_USER_MODEL),
        ),
    ]
