# Generated by Django 3.1 on 2021-11-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0009_auto_20211115_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Enable'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='captchafreq',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
