# Generated by Django 3.2.18 on 2023-05-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0009_bt_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bt',
            name='isserviceprovider',
            field=models.BooleanField(default=False, verbose_name='ServiceProvider'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='isvendor',
            field=models.BooleanField(default=False, verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='iswarehouse',
            field=models.BooleanField(default=False, verbose_name='Warehouse'),
        ),
    ]
