# Generated by Django 3.2.18 on 2024-02-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0009_auto_20240208_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='terminateddate',
            field=models.DateField(null=True, verbose_name='Terminated Date'),
        ),
    ]
