# Generated by Django 3.1 on 2021-11-23 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0005_auto_20211122_1214'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0010_auto_20211122_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(auto_now_add=True, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(auto_now=True, verbose_name='mdtz')),
                ('gfcode', models.CharField(max_length=100, verbose_name='Code')),
                ('gfname', models.CharField(max_length=100, verbose_name='Name')),
                ('alerttext', models.CharField(max_length=100, verbose_name='Alert Text')),
                ('geofence', models.TextField(verbose_name='GeoFence')),
                ('enable', models.BooleanField(default=True, verbose_name='Enable')),
                ('alerttogroup', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='peoples.pgroup', verbose_name='Alert to Group')),
                ('alerttopeople', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='')),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='for_clients', to='onboarding.bt', verbose_name='Client')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='geofencemaster_cusers', to=settings.AUTH_USER_MODEL)),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='geofencemaster_musers', to=settings.AUTH_USER_MODEL)),
                ('siteid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='for_sites', to='onboarding.bt', verbose_name='Site')),
            ],
            options={
                'db_table': 'geofencemaster',
                'ordering': ['mdtz'],
                'get_latest_by': ['mdtz'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='geofencemaster',
            constraint=models.UniqueConstraint(fields=('gfcode', 'siteid'), name='gfcode_siteid_uk'),
        ),
    ]
