# Generated by Django 3.2.18 on 2023-06-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0010_auto_20230512_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractdetail',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='contractdetail',
            name='cuser',
        ),
        migrations.RemoveField(
            model_name='contractdetail',
            name='muser',
        ),
        migrations.RemoveField(
            model_name='contractdetail',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='contractdetail',
            name='worktype',
        ),
        migrations.RemoveField(
            model_name='sitepeople',
            name='bu',
        ),
        migrations.RemoveField(
            model_name='sitepeople',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='sitepeople',
            name='contractdetail',
        ),
        migrations.RemoveField(
            model_name='sitepeople',
            name='cuser',
        ),
        migrations.RemoveField(
            model_name='sitepeople',
            name='muser',
        ),
        migrations.RemoveField(
            model_name='sitepeople',
            name='people',
        ),
        migrations.RemoveField(
            model_name='sitepeople',
            name='reportto',
        ),
        migrations.RemoveField(
            model_name='sitepeople',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='sitepeople',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='sitepeople',
            name='worktype',
        ),
        migrations.RemoveField(
            model_name='wizarddraft',
            name='bu',
        ),
        migrations.RemoveField(
            model_name='wizarddraft',
            name='createdby',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='ContractDetail',
        ),
        migrations.DeleteModel(
            name='SitePeople',
        ),
        migrations.DeleteModel(
            name='WizardDraft',
        ),
    ]
