# Generated by Django 4.2 on 2024-09-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0012_shift_shift_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeassist',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
