# Generated by Django 3.2.4 on 2021-08-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability',
            name='capsid',
            field=models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='people',
            name='peopleid',
            field=models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='peopleid'),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='pelogid',
            field=models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='pelogid'),
        ),
        migrations.AlterField(
            model_name='pgbelonging',
            name='pgbid',
            field=models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pgroup',
            name='groupid',
            field=models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='groupid'),
        ),
    ]
