# Generated by Django 3.1 on 2022-02-11 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_auto_20220211_1222'),
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='people',
            name='peolple_logind_peoplecode_buid_uk',
        ),
        migrations.RemoveConstraint(
            model_name='people',
            name='people_peoplecode_buid',
        ),
        migrations.RemoveConstraint(
            model_name='people',
            name='people_loginid_buid_uk',
        ),
        migrations.RemoveConstraint(
            model_name='pgbelonging',
            name='pgbelonging_groupid_peopleid_buid_assignsites_clientid',
        ),
        migrations.RemoveConstraint(
            model_name='pgroup',
            name='pgroup_groupname_buid_clientid_identifier_key',
        ),
        migrations.RemoveConstraint(
            model_name='pgroup',
            name='pgroup_groupname_buid_identifier_key',
        ),
        migrations.RenameField(
            model_name='capability',
            old_name='clientid',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='pgbelonging',
            old_name='buid',
            new_name='bu',
        ),
        migrations.RenameField(
            model_name='pgbelonging',
            old_name='clientid',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='pgbelonging',
            old_name='peopleid',
            new_name='people',
        ),
        migrations.RenameField(
            model_name='pgbelonging',
            old_name='groupid',
            new_name='pgroup',
        ),
        migrations.RemoveField(
            model_name='people',
            name='buid',
        ),
        migrations.RemoveField(
            model_name='people',
            name='clientid',
        ),
        migrations.RemoveField(
            model_name='pgroup',
            name='buid',
        ),
        migrations.RemoveField(
            model_name='pgroup',
            name='clientid',
        ),
        migrations.AddField(
            model_name='people',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='people_bus', to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='people',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='people_clients', to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='pgroup',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pgroup_bus', to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='pgroup',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pgroup_clients', to='onboarding.bt'),
        ),
        migrations.AddConstraint(
            model_name='people',
            constraint=models.UniqueConstraint(fields=('loginid', 'peoplecode', 'bu'), name='peolple_logind_peoplecode_bu_uk'),
        ),
        migrations.AddConstraint(
            model_name='people',
            constraint=models.UniqueConstraint(fields=('peoplecode', 'bu'), name='people_peoplecode_bu'),
        ),
        migrations.AddConstraint(
            model_name='people',
            constraint=models.UniqueConstraint(fields=('loginid', 'bu'), name='people_loginid_bu_uk'),
        ),
        migrations.AddConstraint(
            model_name='pgbelonging',
            constraint=models.UniqueConstraint(fields=('pgroup', 'people', 'assignsites'), name='pgbelonging_pgroup_people_bu_assignsites_client'),
        ),
        migrations.AddConstraint(
            model_name='pgroup',
            constraint=models.UniqueConstraint(fields=('groupname', 'identifier'), name='pgroup_groupname_bu_client_identifier_key'),
        ),
        migrations.AddConstraint(
            model_name='pgroup',
            constraint=models.UniqueConstraint(fields=('groupname', 'identifier'), name='pgroup_groupname_bu_identifier_key'),
        ),
    ]
