# Generated by Django 3.1 on 2021-10-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability',
            name='capsname',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='capsname'),
        ),
    ]
