# Generated by Django 3.2 on 2022-04-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capability',
            old_name='tzoffset',
            new_name='ctzoffset',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='tzoffset',
            new_name='ctzoffset',
        ),
        migrations.RenameField(
            model_name='pgbelonging',
            old_name='tzoffset',
            new_name='ctzoffset',
        ),
        migrations.RenameField(
            model_name='pgroup',
            old_name='tzoffset',
            new_name='ctzoffset',
        ),
    ]
