# Generated by Django 3.2.14 on 2022-08-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='people',
            name='people_loginid_uk',
        ),
    ]
