# Generated by Django 3.1 on 2021-11-24 06:54

import apps.peoples.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='email',
            field=apps.peoples.models.SecureString(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='people',
            name='mobno',
            field=apps.peoples.models.SecureString(max_length=254, verbose_name='Mob No'),
        ),
        migrations.AddConstraint(
            model_name='people',
            constraint=models.UniqueConstraint(fields=('loginid', 'mobno', 'email'), name='loginid_mobno_email_uk'),
        ),
    ]
