# Generated by Django 3.1 on 2021-11-24 06:57

import apps.peoples.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0002_auto_20211124_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='mobno',
            field=apps.peoples.models.SecureString(max_length=254, null=True, verbose_name='Mob No'),
        ),
    ]
