# Generated by Django 3.2 on 2022-04-16 10:56

import apps.peoples.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0002_auto_20220412_1527'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pgroup',
            managers=[
                ('objects', apps.peoples.managers.PgroupManager()),
            ],
        ),
    ]
