# Generated by Django 3.1 on 2021-09-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0002_auto_20210828_1451'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='people',
            constraint=models.UniqueConstraint(fields=('loginid',), name='people_loginid_uk'),
        ),
    ]
