# Generated by Django 3.1 on 2021-11-08 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0002_auto_20211019_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability',
            name='capscode',
            field=models.CharField(max_length=50, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='capability',
            name='capsname',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Capability'),
        ),
        migrations.AlterField(
            model_name='capability',
            name='cfor',
            field=models.CharField(choices=[('WEB', 'WEB'), ('PORTLET', 'PORTLET'), ('REPORT', 'REPORT'), ('MOB', 'MOB')], default='WEB', max_length=10, verbose_name='Capability_for'),
        ),
        migrations.AlterField(
            model_name='capability',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='peoples.capability', verbose_name='Belongs_to'),
        ),
    ]
