# Generated by Django 3.1 on 2022-01-22 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_auto_20220122_1132'),
        ('peoples', '0002_auto_20220118_1723'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='people',
            name='peolple_logind_peoplecode_siteid_uk',
        ),
        migrations.RemoveConstraint(
            model_name='people',
            name='people_peoplecode_siteid',
        ),
        migrations.RemoveConstraint(
            model_name='people',
            name='people_loginid_siteid_uk',
        ),
        migrations.RenameField(
            model_name='pgbelonging',
            old_name='siteid',
            new_name='buid',
        ),
        migrations.RemoveField(
            model_name='people',
            name='siteid',
        ),
        migrations.RemoveField(
            model_name='pgroup',
            name='siteid',
        ),
        migrations.AddField(
            model_name='people',
            name='buid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='people_buids', to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='pgroup',
            name='buid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pgroup_buids', to='onboarding.bt'),
        ),
        migrations.AddConstraint(
            model_name='people',
            constraint=models.UniqueConstraint(fields=('loginid', 'peoplecode', 'buid'), name='peolple_logind_peoplecode_buid_uk'),
        ),
        migrations.AddConstraint(
            model_name='people',
            constraint=models.UniqueConstraint(fields=('peoplecode', 'buid'), name='people_peoplecode_buid'),
        ),
        migrations.AddConstraint(
            model_name='people',
            constraint=models.UniqueConstraint(fields=('loginid', 'buid'), name='people_loginid_buid_uk'),
        ),
    ]
