# Generated by Django 3.2.18 on 2023-07-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0002_alter_people_loginid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='loginid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Login Id'),
        ),
    ]
