# Generated by Django 3.2.14 on 2022-08-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0002_remove_people_people_loginid_uk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=15, null=True, verbose_name='Gender'),
        ),
    ]
