# Generated by Django 3.2.18 on 2023-08-16 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0003_alter_people_loginid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgroup',
            name='grouplead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pgroup_groupleads', to=settings.AUTH_USER_MODEL),
        ),
    ]
