# Generated by Django 3.1 on 2021-11-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0003_auto_20211124_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
    ]
