# Generated by Django 3.1 on 2021-09-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0003_auto_20210916_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15, null=True, verbose_name='gender'),
        ),
    ]
