# Generated by Django 3.2.14 on 2022-10-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0003_alter_people_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='dateofjoin',
            field=models.DateField(null=True, verbose_name='Date of Join'),
        ),
    ]
