# Generated by Django 3.1 on 2021-11-15 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0009_auto_20211115_1614'),
        ('peoples', '0003_auto_20211108_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability',
            name='clientid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt'),
        ),
        migrations.AlterField(
            model_name='capability',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='capability_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='capability',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='capability_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='capability',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='peoples.capability', verbose_name='Belongs_to'),
        ),
        migrations.AlterField(
            model_name='people',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='people_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='people',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='people_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='buid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt'),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='clientid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='clientids', to='onboarding.bt'),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='peopleeventlog_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='peopleeventlog_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='peopleid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='peventtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='eventypes', to='onboarding.typeassist'),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='punchstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='statustypes', to='onboarding.typeassist'),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='siteid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='siteids', to='onboarding.bt'),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='transportmode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transportmodetypes', to='onboarding.typeassist'),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='verifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='verifiedpeoples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pgbelonging',
            name='assignsites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pgbelongs_assignsites', to='onboarding.bt'),
        ),
        migrations.AlterField(
            model_name='pgbelonging',
            name='clientid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pgbelonging_clients', to='onboarding.bt'),
        ),
        migrations.AlterField(
            model_name='pgbelonging',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pgbelonging_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pgbelonging',
            name='groupid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pgbelongs_grps', to='peoples.pgroup'),
        ),
        migrations.AlterField(
            model_name='pgbelonging',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pgbelonging_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pgbelonging',
            name='peopleid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pgbelongs_peoples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pgbelonging',
            name='siteid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pgbelonging_sites', to='onboarding.bt'),
        ),
        migrations.AlterField(
            model_name='pgroup',
            name='clientid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pgroup_clientids', to='onboarding.bt'),
        ),
        migrations.AlterField(
            model_name='pgroup',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pgroup_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pgroup',
            name='identifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pgroup_idfs', to='onboarding.typeassist'),
        ),
        migrations.AlterField(
            model_name='pgroup',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pgroup_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pgroup',
            name='siteid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pgroup_siteids', to='onboarding.bt'),
        ),
    ]
