# Generated by Django 3.1 on 2021-11-22 06:44

import apps.peoples.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0010_auto_20211122_1214'),
        ('peoples', '0004_auto_20211115_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='isenable',
        ),
        migrations.AddField(
            model_name='capability',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Enable'),
        ),
        migrations.AddField(
            model_name='people',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Enable'),
        ),
        migrations.AlterField(
            model_name='people',
            name='dateofbirth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='people',
            name='dateofjoin',
            field=models.DateField(verbose_name='Date of Join'),
        ),
        migrations.AlterField(
            model_name='people',
            name='dateofreport',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Report'),
        ),
        migrations.AlterField(
            model_name='people',
            name='deviceid',
            field=models.CharField(default='-1', max_length=50, verbose_name='Device Id'),
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=apps.peoples.models.SecureString(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='people',
            name='isadmin',
            field=models.BooleanField(default=False, verbose_name='Is Admin'),
        ),
        migrations.AlterField(
            model_name='people',
            name='loginid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Login Id'),
        ),
        migrations.AlterField(
            model_name='people',
            name='mobno',
            field=apps.peoples.models.SecureString(max_length=254, unique=True, verbose_name='Mob No'),
        ),
        migrations.AlterField(
            model_name='people',
            name='peoplecode',
            field=models.CharField(max_length=50, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='people',
            name='peoplename',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='people',
            name='peopletype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='people_types', to='onboarding.typeassist', verbose_name='People Type'),
        ),
        migrations.AlterField(
            model_name='people',
            name='reportto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Report to'),
        ),
        migrations.AlterField(
            model_name='pgbelonging',
            name='isgrouplead',
            field=models.BooleanField(default=False, verbose_name='Group Lead'),
        ),
        migrations.AlterField(
            model_name='pgroup',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Enable'),
        ),
        migrations.AlterField(
            model_name='pgroup',
            name='groupname',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
    ]
