# Generated by Django 3.1 on 2021-09-21 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_auto_20210828_1451'),
        ('peoples', '0004_auto_20210921_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='onboarding_shift', to='onboarding.shift'),
        ),
    ]
