# Generated by Django 3.2.14 on 2022-10-13 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_initial'),
        ('peoples', '0004_alter_people_dateofjoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='worktype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='work_types', to='onboarding.typeassist', verbose_name='Work Type'),
        ),
    ]
