# Generated by Django 3.1 on 2021-11-23 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0011_auto_20211123_1307'),
        ('peoples', '0005_auto_20211122_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peopleeventlog',
            name='buid',
        ),
        migrations.RemoveField(
            model_name='peopleeventlog',
            name='gpslocation',
        ),
        migrations.RemoveField(
            model_name='peopleeventlog',
            name='otherlocation',
        ),
        migrations.RemoveField(
            model_name='peopleeventlog',
            name='punchstatus',
        ),
        migrations.RemoveField(
            model_name='peopleeventlog',
            name='reference',
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='gfid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.geofencemaster'),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='gpslocation_in',
            field=models.CharField(default='0.0,0.0', max_length=50, verbose_name='GPS-In'),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='gpslocation_out',
            field=models.CharField(default='0.0,0.0', max_length=50, verbose_name='GPS-Out'),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='punch_intime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='punch_outtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.shift'),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='distance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Distance'),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='peventtype',
            field=models.CharField(choices=[('MARK', 'Mark'), ('SELF', 'Self'), ('SITE', 'Site'), ('CONVEYANCE', 'Conveyance')], max_length=100, null=True, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='transportmode',
            field=models.CharField(choices=[('BICYCLE', 'Bicycle'), ('MOTORCYCLE', 'MotorCycle'), ('RICKSHAW', 'Rickshaw'), ('BUS', 'Bus'), ('TRAIN', 'Train'), ('FLITE', 'Flite'), ('BOAT', 'Boat or Ship')], max_length=100, null=True, verbose_name='Transport Mode'),
        ),
    ]
