# Generated by Django 4.2 on 2025-01-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0005_alter_capability_cuser_alter_capability_muser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability',
            name='cfor',
            field=models.CharField(choices=[('WEB', 'WEB'), ('PORTLET', 'PORTLET'), ('REPORT', 'REPORT'), ('MOB', 'MOB'), ('NOC', 'NOC')], default='WEB', max_length=10, verbose_name='Capability_for'),
        ),
    ]
