# Generated by Django 3.2.14 on 2023-01-24 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_auto_20230124_1619'),
        ('peoples', '0005_people_worktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='people_departments', to='onboarding.typeassist', verbose_name='Department'),
        ),
    ]
