# Generated by Django 3.2.14 on 2023-01-24 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_auto_20230124_1619'),
        ('peoples', '0006_alter_people_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt', verbose_name='BV'),
        ),
        migrations.AlterField(
            model_name='people',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='people_bus', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='people',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='people_clients', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='people',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='people_designations', to='onboarding.typeassist', verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='pgroup',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pgroup_bus', to='onboarding.bt', verbose_name='BV'),
        ),
        migrations.AlterField(
            model_name='pgroup',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pgroup_clients', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='pgroup',
            name='identifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pgroup_idfs', to='onboarding.typeassist', verbose_name='Identifier'),
        ),
    ]
