# Generated by Django 3.1 on 2021-11-23 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0006_auto_20211123_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peopleeventlog',
            name='datetime',
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='datefor',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='facerecognition',
            field=models.BooleanField(default=True, verbose_name='Enable Face-Recognition'),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='peopleid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='People'),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='peventtype',
            field=models.CharField(choices=[('MARK', 'Mark'), ('SELF', 'Self'), ('SITE', 'Site'), ('CONVEYANCE', 'Conveyance')], max_length=100, null=True, verbose_name='Attendance Type'),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='verifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='verifiedpeoples', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
    ]
