# Generated by Django 3.1 on 2021-11-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0007_auto_20211123_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleeventlog',
            name='punch_intime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='punch_outtime',
            field=models.DateTimeField(null=True),
        ),
    ]
