# Generated by Django 3.2.14 on 2023-03-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0007_auto_20230124_1622'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='people',
            name='loginid_mobno_email_uk',
        ),
        migrations.AddConstraint(
            model_name='people',
            constraint=models.UniqueConstraint(fields=('loginid', 'mobno', 'email', 'bu'), name='loginid_mobno_email_bu_uk'),
        ),
    ]
