# Generated by Django 3.2.14 on 2023-03-02 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0035_attachment_size'),
        ('peoples', '0008_auto_20230302_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.location', verbose_name='Location'),
        ),
    ]
