# Generated by Django 3.2.14 on 2023-03-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0009_people_location'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='capability',
            name='capability_caps_cfor_uk',
        ),
        migrations.RemoveConstraint(
            model_name='pgbelonging',
            name='pgbelonging_pgroup_people_bu_assignsites_client',
        ),
        migrations.RemoveConstraint(
            model_name='pgroup',
            name='pgroup_groupname_bu_client_identifier_key',
        ),
        migrations.RemoveConstraint(
            model_name='pgroup',
            name='pgroup_groupname_bu_identifier_key',
        ),
        migrations.AddConstraint(
            model_name='capability',
            constraint=models.UniqueConstraint(fields=('capscode', 'cfor', 'client'), name='capability_caps_cfor_uk'),
        ),
        migrations.AddConstraint(
            model_name='pgbelonging',
            constraint=models.UniqueConstraint(fields=('pgroup', 'people', 'assignsites', 'client'), name='pgbelonging_pgroup_people_bu_assignsites_client'),
        ),
        migrations.AddConstraint(
            model_name='pgroup',
            constraint=models.UniqueConstraint(fields=('groupname', 'identifier', 'client'), name='pgroup_groupname_bu_client_identifier_key'),
        ),
        migrations.AddConstraint(
            model_name='pgroup',
            constraint=models.UniqueConstraint(fields=('groupname', 'identifier', 'client'), name='pgroup_groupname_bu_identifier_key'),
        ),
    ]
