# Generated by Django 3.2.18 on 2023-05-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0010_auto_20230313_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='isadmin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='people',
            name='isverified',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
