"""
Django settings for intelliwiz_config project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from django.http import request
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z8zcu0*td9qe$nuh*ly-mpwt&x@h%0+so$hc$lp)g_1x+#0l9_'
SECRET_SALT = "ijsafifd343433jffd"
ENCRYPT_KEY = 'I618zPOcrQ3zB5XasmuLXazlGZUn-dK5anHXSvKs4dM='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.localhost', '.youtility.local', 'barfi.youtility.in', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #third_party_apps
    'debug_toolbar',
    'import_export',
    'django_extensions',
    "django_select2",
    'django_filters',

    #local apps
    'apps.peoples',
    'apps.onboarding',
    'apps.tenants',
]

MIDDLEWARE = [
    'apps.tenants.middlewares.TenantMiddleware', #custom middleware
    'django.middleware.security.SecurityMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'intelliwiz_config.urls'
JINJA_TEMPLATES = os.path.join(BASE_DIR, 'frontend/templates')
import jinja2
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
               
            ],
            
        },
    },
    #jinja2 configuration
    { 
        'BACKEND':'django.template.backends.jinja2.Jinja2',
        'DIRS': [JINJA_TEMPLATES],
        'APP_DIRS': True,
        'OPTIONS':{
            'extensions': ['jinja2.ext.loopcontrols',],
            'autoescape' : False,
            'auto_reload': True,
            'undefined'  : jinja2.StrictUndefined,
            'environment': 'intelliwiz_config.jinja.env.JinjaEnvironment'
        },
    },
]


WSGI_APPLICATION = 'intelliwiz_config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

#multi database configuration.
'''
NOTE: Client bucode should match the database alias name.
'''
youtility_dbs = {
    'default': {
        'ENGINE':   'django.db.backends.postgresql_psycopg2',
        'USER':     'youtilitydba',
        'NAME':     'intelliwiz_django',
        'PASSWORD': '!!sysadmin!!',
        'HOST':     '192.168.1.254',
        'PORT':     '5432',
    },
    'sps':{
        'ENGINE':   'django.db.backends.postgresql_psycopg2',
        'USER':     'youtilitydba',
        'NAME':     'sps',
        'PASSWORD': '!!sysadmin!!',
        'HOST':     '192.168.1.254',
        'PORT':     '5432',
    },
    'icici':{
        'ENGINE':   'django.db.backends.postgresql_psycopg2',
        'USER':     'youtilitydba',
        'NAME':     'icici',
        'PASSWORD': '!!sysadmin!!',
        'HOST':     '192.168.1.254',
        'PORT':     '5432',
    }
}



home_local_dbs = {
    'default': {
        'ENGINE':   'django.db.backends.postgresql_psycopg2',
        'USER':     'youtilitydba',
        'NAME':     'intelliwiz_django',
        'PASSWORD': 'root',
        'HOST':     'localhost',
        'PORT':     '',
    },
    'sps':{
        'ENGINE':   'django.db.backends.postgresql_psycopg2',
        'USER':     'youtilitydba',
        'NAME':     'sps',
        'PASSWORD': 'root',
        'HOST':     'localhost',
        'PORT':     '',
    },
    'icici':{
        'ENGINE':   'django.db.backends.postgresql_psycopg2',
        'USER':     'youtilitydba',
        'NAME':     'icici',
        'PASSWORD': 'root',
        'HOST':     'localhost',
        'PORT':     '',
    }
}


DATABASES = youtility_dbs

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
       "KEY_PREFIX": "youtility4"
    },
    "select2": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
       "KEY_PREFIX": "select2"
    }
}

SELECT2_CACHE_BACKEND = 'select2'
SELECT2_JS = ""
SELECT2_CSS = ""
SELECT2_I18N_PATH = 'assets/plugins/custom/select2-4.x/js/i18n'

# Cache time to live is 15 minutes.
CACHE_TTL = 60 * 5

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'intelliwiz_config/static')]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATABASE_ROUTERS = ['apps.tenants.middlewares.TenantDbRouter']

# Media Files
MEDIA_ROOT = os.path.join(os.path.expanduser('~'),'youtility4_media')
MEDIA_URL = '/youtility4_media/'
DATE_FORMAT = "d M Y"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'frontend/static')]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATABASE_ROUTERS = ['apps.tenants.middlewares.TenantDbRouter']

# Media Files

INTERNAL_IPS = [
    # ...
    '127.0.0.1',
    # ...
]


AUTH_USER_MODEL = 'peoples.People'
AUTHENTICATION_BACKENDS = ('apps.peoples.backends.MultiAuthentcationBackend',
'django.contrib.auth.backends.ModelBackend')



import logging.config
LOGGING_CONFIG = None
LOGGING_CONFIG_ = { 
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': { 
        'coloured': { 
            '()': 'colorlog.ColoredFormatter',
            'format': '%(log_color)s %(asctime)s [%(levelname)s] %(name)s:  from method: %(funcName)s()   %(message)s '
        },
    },
    'handlers': { 
        'default': { 
            #'level': 'INFO',
            'formatter': 'coloured',
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',  # Default is stderr
        },
    },
    'loggers': { 
        '': {  # root logger
            'handlers': ['default'],
            'level': 'WARNING',
            'propagate': False
        },
        'django': { 
            'handlers': ['default'],
            'level': 'INFO',
            'propagate': False
        },
        '__main__': {  # if __name__ == '__main__'
            'handlers': ['default'],
            'level': 'DEBUG',
            'propagate': False
        },
    } 
}
logging.config.dictConfig(LOGGING_CONFIG_)

LOGIN_URL = 'login'

SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
# Close the session when user closes the browser
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 30 * 60  # set just 10 seconds to test
SESSION_SAVE_EVERY_REQUEST = True
IMPORT_EXPORT_USE_TRANSACTIONS = True





