# Generated by Django 3.2.14 on 2023-02-03 10:08

import apps.peoples.models
import apps.y_helpdesk.managers
import apps.y_helpdesk.models
from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0033_auto_20230203_1538'),
        ('onboarding', '0006_auto_20230124_1619'),
        ('peoples', '0007_auto_20230124_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('cdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='mdtz')),
                ('ctzoffset', models.IntegerField(default=-1, verbose_name='TimeZone')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, unique=True)),
                ('ticketno', apps.y_helpdesk.models.TicketNumberField(primary_key=True, serialize=False)),
                ('ticketdesc', models.CharField(max_length=250)),
                ('comments', models.CharField(max_length=250, null=True)),
                ('priority', models.CharField(blank=True, choices=[('HIGH', 'High'), ('LOW', 'Low'), ('MEDIUM', 'Medium')], max_length=50, null=True, verbose_name='Priority')),
                ('escalationtemplate', models.CharField(blank=True, max_length=30, null=True)),
                ('modifieddatetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('NEW', 'New'), ('CANCEL', 'Cancel'), ('CLOSE', 'Close'), ('ESCALATED', 'Escalated'), ('AUTOCLOSE', 'Autoclose'), ('ASSIGNED', 'Assigned')], max_length=50, null=True, verbose_name='Status')),
                ('ticketlog', models.JSONField(blank=True, default=apps.y_helpdesk.models.ticket_defaults, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('events', models.TextField(blank=True, null=True)),
                ('isescalated', models.BooleanField(default=True)),
                ('ticketsource', models.CharField(blank=True, choices=[('SYSTEMGENERATED', 'New Generated'), ('USERDEFINED', 'User Defined')], max_length=50, null=True)),
                ('assignedtogroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_grps', to='peoples.pgroup')),
                ('assignedtopeople', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_people', to=settings.AUTH_USER_MODEL)),
                ('bu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_cusers', to=settings.AUTH_USER_MODEL)),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_musers', to=settings.AUTH_USER_MODEL)),
                ('performedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_performedby', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'ticket',
                'ordering': ['mdtz'],
                'get_latest_by': ['cdtz', 'mdtz'],
                'abstract': False,
            },
            managers=[
                ('objects', apps.y_helpdesk.managers.TicketManager()),
            ],
        ),
        migrations.CreateModel(
            name='EscalationMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='mdtz')),
                ('ctzoffset', models.IntegerField(default=-1, verbose_name='TimeZone')),
                ('body', models.CharField(max_length=500, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('MINUTE', 'MINUTE'), ('HOUR', 'HOUR'), ('DAY', 'DAY'), ('WEEK', 'WEEK')], default='DAY', max_length=10)),
                ('frequencyvalue', models.IntegerField(blank=True, null=True)),
                ('assignedfor', models.CharField(max_length=50)),
                ('notify', models.TextField(blank=True, null=True)),
                ('assignedgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='escalation_grps', to='peoples.pgroup')),
                ('assignedperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='escalation_people', to=settings.AUTH_USER_MODEL)),
                ('bu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='esc_clients', to='onboarding.bt')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='escalationmatrix_cusers', to=settings.AUTH_USER_MODEL)),
                ('escalationtemplate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='esc_types', to='onboarding.typeassist')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.job', verbose_name='Job')),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='escalationmatrix_musers', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'escalationmatrix',
                'ordering': ['mdtz'],
                'get_latest_by': ['mdtz', 'cdtz'],
                'abstract': False,
            },
            managers=[
                ('objects', apps.y_helpdesk.managers.ESCManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('bu', 'ticketno'), name='bu_ticketno_uk'),
        ),
    ]
