# Generated by Django 3.2.14 on 2023-02-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y_helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='isescalated',
            field=models.BooleanField(default=False),
        ),
    ]
