# Generated by Django 3.2.14 on 2023-02-03 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_auto_20230124_1619'),
        ('y_helpdesk', '0002_alter_ticket_isescalated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='escalationtemplate',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticketcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticketcategory_types', to='onboarding.typeassist'),
        ),
    ]
