# Generated by Django 3.2.18 on 2023-08-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y_helpdesk', '0002_auto_20230627_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticketdesc',
            field=models.TextField(),
        ),
    ]
