# Generated by Django 3.2.14 on 2023-02-03 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0033_auto_20230203_1538'),
        ('y_helpdesk', '0003_auto_20230203_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.location'),
        ),
    ]
