# Generated by Django 4.2 on 2024-09-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y_helpdesk', '0004_alter_escalationmatrix_cuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalationmatrix',
            name='notify',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddConstraint(
            model_name='escalationmatrix',
            constraint=models.CheckConstraint(check=models.Q(('frequencyvalue__gte', 0)), name='frequencyvalue_gte_0_ck'),
        ),
        migrations.AddConstraint(
            model_name='escalationmatrix',
            constraint=models.CheckConstraint(check=models.Q(('notify__isnull', True), ('notify', ''), ('notify__regex', '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$'), _connector='OR'), name='valid_notify_format'),
        ),
    ]
