# Generated by Django 3.2.14 on 2023-02-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('y_helpdesk', '0004_ticket_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticketno',
            new_name='id',
        ),
    ]
