# Generated by Django 3.2.14 on 2023-02-04 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_auto_20230124_1619'),
        ('y_helpdesk', '0005_rename_ticketno_ticket_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='bu_ticketno_uk',
        ),
        migrations.AddField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_clients', to='onboarding.bt'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('bu', 'id'), name='bu_id_uk'),
        ),
    ]
