# Generated by Django 3.2.14 on 2023-02-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y_helpdesk', '0006_auto_20230204_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('CANCEL', 'Cancel'), ('CLOSE', 'Close'), ('ESCALATED', 'Escalated'), ('AUTOCLOSE', 'Autoclose'), ('ASSIGNED', 'Assigned')], default='NEW', max_length=50, null=True, verbose_name='Status'),
        ),
    ]
