# Generated by Django 3.2.14 on 2023-02-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y_helpdesk', '0007_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('CANCELLED', 'Cancel'), ('RESOLVED', 'Resolved'), ('OPEN', 'Open')], default='NEW', max_length=50, null=True, verbose_name='Status'),
        ),
    ]
