# Generated by Django 3.2.14 on 2023-02-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y_helpdesk', '0009_alter_ticket_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachmentcount',
            field=models.IntegerField(null=True),
        ),
    ]
