# Generated by Django 3.2.14 on 2023-03-03 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0035_attachment_size'),
        ('y_helpdesk', '0010_ticket_attachmentcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.asset'),
        ),
    ]
