# Generated by Django 3.2.14 on 2023-03-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y_helpdesk', '0011_ticket_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('CANCELLED', 'Cancel'), ('RESOLVED', 'Resolved'), ('OPEN', 'Open'), ('ONHOLD', 'On Hold'), ('CLOSED', 'Closed')], default='NEW', max_length=50, null=True, verbose_name='Status'),
        ),
    ]
