# Generated by Django 3.2.14 on 2023-03-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y_helpdesk', '0012_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='bu_id_uk',
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('bu', 'id', 'client'), name='bu_id_uk'),
        ),
    ]
