# Generated by Django 3.2.18 on 2023-04-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y_helpdesk', '0013_auto_20230313_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='identifier',
            field=models.CharField(choices=[('REQUEST', 'Request'), ('TICKET', 'Ticket')], default='TICKET', max_length=50, verbose_name='Identifier'),
        ),
    ]
