# Generated by Django 3.2.18 on 2023-06-03 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0061_auto_20230601_0139'),
        ('y_helpdesk', '0014_ticket_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.questionset'),
        ),
    ]
