# Generated by Django 3.2 on 2022-03-08 05:58

import apps.attendance.models
import django.contrib.gis.db.models.fields
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleEventlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(auto_now_add=True, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(auto_now=True, verbose_name='mdtz')),
                ('transportmodes', models.TextField(max_length=500, null=True)),
                ('punch_intime', models.DateTimeField(null=True)),
                ('punch_outtime', models.DateTimeField(null=True)),
                ('datefor', models.DateField(null=True, verbose_name='Date')),
                ('distance', models.IntegerField(blank=True, null=True, verbose_name='Distance')),
                ('expamt', models.FloatField(blank=True, default=0.0, null=True, verbose_name='exampt')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='duration')),
                ('accuracy', models.IntegerField(blank=True, null=True, verbose_name='accuracy')),
                ('deviceid', models.CharField(blank=True, max_length=50, null=True, verbose_name='deviceid')),
                ('startlocation', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326, verbose_name='GPS-In')),
                ('endlocation', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326, verbose_name='GPS-Out')),
                ('journeypath', django.contrib.gis.db.models.fields.LineStringField(geography=True, null=True, srid=4326)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='remarks')),
                ('facerecognition', models.BooleanField(default=True, verbose_name='Enable Face-Recognition')),
                ('peventlogextras', models.JSONField(default=apps.attendance.models.peventlog_json, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='peventlogextras')),
            ],
            options={
                'db_table': 'people_eventlog',
                'ordering': ['mdtz'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestGeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(geography=True, null=True, srid=4326)),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
                ('line', django.contrib.gis.db.models.fields.LineStringField(geography=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(max_length=40)),
                ('gpslocation', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('reference', models.IntegerField()),
                ('recieveddate', models.DateTimeField()),
                ('transportmode', models.CharField(max_length=55)),
                ('amount', models.FloatField(default=0.0)),
            ],
        ),
    ]
