# Generated by Django 3.1 on 2021-11-24 06:46

import apps.attendance.models
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleEventlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(auto_now_add=True, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(auto_now=True, verbose_name='mdtz')),
                ('peventtype', models.CharField(choices=[('MARK', 'Mark'), ('SELF', 'Self'), ('SITE', 'Site'), ('CONVEYANCE', 'Conveyance')], max_length=100, null=True, verbose_name='Attendance Type')),
                ('transportmode', models.CharField(choices=[('BICYCLE', 'Bicycle'), ('MOTORCYCLE', 'MotorCycle'), ('RICKSHAW', 'Rickshaw'), ('BUS', 'Bus'), ('TRAIN', 'Train'), ('FLITE', 'Flite'), ('BOAT', 'Boat or Ship')], max_length=100, null=True, verbose_name='Transport Mode')),
                ('punch_intime', models.DateTimeField(null=True)),
                ('punch_outtime', models.DateTimeField(null=True)),
                ('datefor', models.DateField(null=True, verbose_name='Date')),
                ('distance', models.IntegerField(blank=True, null=True, verbose_name='Distance')),
                ('ctzoffset', models.IntegerField(blank=True, default=0, null=True, verbose_name='ctzoffset')),
                ('expamt', models.IntegerField(blank=True, null=True, verbose_name='exampt')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='duration')),
                ('accuracy', models.IntegerField(blank=True, null=True, verbose_name='accuracy')),
                ('deviceid', models.CharField(blank=True, max_length=50, null=True, verbose_name='deviceid')),
                ('gpslocation_in', models.CharField(default='0.0,0.0', max_length=50, verbose_name='GPS-In')),
                ('gpslocation_out', models.CharField(default='0.0,0.0', max_length=50, verbose_name='GPS-Out')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='remarks')),
                ('facerecognition', models.BooleanField(default=True, verbose_name='Enable Face-Recognition')),
                ('peventlogextras', models.JSONField(default=apps.attendance.models.peventlog_json, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='peventlogextras')),
            ],
            options={
                'ordering': ['mdtz'],
                'abstract': False,
            },
        ),
    ]
