# Generated by Django 3.2.14 on 2022-10-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peopleeventlog',
            name='facerecognition',
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='facerecognition_in',
            field=models.BooleanField(default=False, verbose_name='Enable Face-Recognition In'),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='facerecognition_out',
            field=models.BooleanField(default=False, verbose_name='Enable Face-Recognition Out'),
        ),
    ]
