# Generated by Django 3.1 on 2021-11-24 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleeventlog',
            name='clientid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='clientids', to='onboarding.bt'),
        ),
    ]
