# Generated by Django 3.2 on 2022-05-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='identifier',
        ),
    ]
