# Generated by Django 3.2.14 on 2022-10-29 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20221028_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peopleeventlog',
            old_name='facerecognition_in',
            new_name='facerecognitionin',
        ),
        migrations.RenameField(
            model_name='peopleeventlog',
            old_name='facerecognition_out',
            new_name='facerecognitionout',
        ),
    ]
