# Generated by Django 3.1 on 2021-11-24 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0002_peopleeventlog_clientid'),
        ('tenants', '0001_initial'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleeventlog',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='peopleeventlog_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='gfid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.geofencemaster'),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='peopleeventlog_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='peopleid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='People'),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.shift'),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='siteid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='siteids', to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='verifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='verifiedpeoples', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
    ]
