# Generated by Django 3.2.18 on 2023-08-16 07:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_peopleeventlog_otherlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='gpslocation',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
    ]
