# Generated by Django 3.2 on 2022-04-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peopleeventlog',
            old_name='tzoffset',
            new_name='ctzoffset',
        ),
    ]
