# Generated by Django 3.2 on 2022-03-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tracking',
            table='tracking',
        ),
    ]
