# Generated by Django 3.1 on 2022-02-11 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_auto_20220211_1222'),
        ('attendance', '0003_auto_20220201_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peopleeventlog',
            old_name='gfid',
            new_name='geofence',
        ),
        migrations.RenameField(
            model_name='peopleeventlog',
            old_name='peopleid',
            new_name='people',
        ),
        migrations.RemoveField(
            model_name='peopleeventlog',
            name='buid',
        ),
        migrations.RemoveField(
            model_name='peopleeventlog',
            name='clientid',
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bus', to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='clients', to='onboarding.bt'),
        ),
    ]
