# Generated by Django 3.2.14 on 2022-11-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20221029_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleeventlog',
            name='facerecognitionin',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Enable Face-Recognition In'),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='facerecognitionout',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Enable Face-Recognition Out'),
        ),
    ]
