# Generated by Django 3.2 on 2022-06-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_rename_recieveddate_tracking_receiveddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='amount',
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Distance'),
        ),
    ]
