# Generated by Django 3.2.14 on 2022-12-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20221115_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='identifier',
            field=models.CharField(choices=[('NONE', 'None'), ('CONVEYANCE', 'Conveyance'), ('EXTERNALTOUR', 'External Tour'), ('SITEVISIT', 'Site Visit'), ('TRACKING', 'Tracking')], default='NONE', max_length=55),
        ),
    ]
