# Generated by Django 3.2 on 2022-03-19 10:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_tracking_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleeventlog',
            name='endlocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='GPS-Out'),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='punch_intime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='punch_outtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='transportmodes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='recieveddate',
            field=models.DateTimeField(null=True),
        ),
    ]
