# Generated by Django 3.1 on 2022-02-28 13:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20220211_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleeventlog',
            name='gpslocation_in',
            field=django.contrib.gis.db.models.fields.PointField(max_length=50, srid=4326, verbose_name='GPS-In'),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='gpslocation_out',
            field=django.contrib.gis.db.models.fields.PointField(max_length=50, srid=4326, verbose_name='GPS-Out'),
        ),
    ]
