# Generated by Django 3.2 on 2022-06-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20220602_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='reference',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
