# Generated by Django 3.1 on 2022-01-22 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_auto_20220122_1132'),
        ('attendance', '0004_auto_20220118_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peopleeventlog',
            name='siteid',
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='buid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='buids', to='onboarding.bt'),
        ),
    ]
