# Generated by Django 3.2.18 on 2023-12-07 07:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_tracking_gpslocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleeventlog',
            name='startlocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='GPS-In'),
        ),
        migrations.AlterField(
            model_name='testgeo',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='gpslocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
