# Generated by Django 3.2 on 2022-04-23 09:28

import apps.attendance.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_rename_tzoffset_peopleeventlog_ctzoffset'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='peopleeventlog',
            managers=[
                ('objects', apps.attendance.managers.PELManager()),
            ],
        ),
    ]
