# Generated by Django 3.2 on 2022-03-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20220319_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peopleeventlog',
            name='punch_intime',
        ),
        migrations.RemoveField(
            model_name='peopleeventlog',
            name='punch_outtime',
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='punchintime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='punchouttime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
