# Generated by Django 3.2 on 2022-06-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_tracking_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='identifier',
            field=models.CharField(choices=[('NONE', 'None'), ('CONVEYANCE', 'Conveyance'), ('EXTERNALTOUR', 'External Tour'), ('SITEVISIT', 'Site Visit')], default='NONE', max_length=55),
        ),
    ]
