# Generated by Django 3.2.14 on 2022-12-14 07:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_tracking_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleeventlog',
            name='transportmodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('BIKE', 'Bike'), ('RICKSHAW', 'Rickshaw'), ('BUS', 'Bus'), ('TRAIN', 'Train'), ('TRAM', 'Tram'), ('PLANE', 'Plane'), ('FERRY', 'Ferry'), ('NONE', 'NONE'), ('CAR', 'Car'), ('TAXI', 'Taxi'), ('OLA_UBER', 'Ola/Uber')], default='NONE', max_length=50), default=list, size=None),
        ),
    ]
