# Generated by Django 3.2 on 2022-03-04 10:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20220228_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peopleeventlog',
            name='gpslocation_in',
        ),
        migrations.RemoveField(
            model_name='peopleeventlog',
            name='gpslocation_out',
        ),
        migrations.RemoveField(
            model_name='peopleeventlog',
            name='transportmode',
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='endlocation',
            field=django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326, verbose_name='GPS-Out'),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='startlocation',
            field=django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326, verbose_name='GPS-In'),
        ),
        migrations.AddField(
            model_name='peopleeventlog',
            name='transportmodes',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
