# Generated by Django 3.2 on 2022-06-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_tracking_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleeventlog',
            name='accuracy',
            field=models.FloatField(blank=True, null=True, verbose_name='accuracy'),
        ),
    ]
