# Generated by Django 3.2.14 on 2022-12-21 12:34

import apps.attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_peopleeventlog_transportmodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleeventlog',
            name='peopleeventloggeojson',
            field=models.JSONField(default=apps.attendance.models.pel_geojson, null=True),
        ),
    ]
