# Generated by Django 3.2 on 2022-03-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20220304_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleeventlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
