# Generated by Django 4.2 on 2024-03-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_peopleeventlog_cuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='identifier',
            field=models.CharField(choices=[('NONE', 'None'), ('CONVEYANCE', 'Conveyance'), ('EXTERNALTOUR', 'External Tour'), ('INTERNALTOUR', 'Internal Tour'), ('SITEVISIT', 'Site Visit'), ('TRACKING', 'Tracking')], default='NONE', max_length=55),
        ),
    ]
