# Generated by Django 3.2 on 2022-06-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_peopleeventlog_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleeventlog',
            name='reference',
            field=models.CharField(max_length=55, null=True, verbose_name='Reference'),
        ),
    ]
