# Generated by Django 3.2.14 on 2022-12-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_peopleeventlog_peopleeventloggeojson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peopleeventlog',
            old_name='peopleeventloggeojson',
            new_name='geojson',
        ),
    ]
