# Generated by Django 3.2.14 on 2022-12-29 07:21

import apps.attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_rename_peopleeventloggeojson_peopleeventlog_geojson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleeventlog',
            name='geojson',
            field=models.JSONField(blank=True, default=apps.attendance.models.pel_geojson, null=True),
        ),
    ]
