# Generated by Django 3.2 on 2022-06-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_peopleeventlog_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleeventlog',
            name='transportmodes',
            field=models.TextField(blank=True, choices=[('BICYCLE', 'Bicycle'), ('MOTORCYCLE', 'MotorCycle'), ('RICKSHAW', 'Rickshaw'), ('BUS', 'Bus'), ('TRAIN', 'Train'), ('FLITE', 'Flite'), ('BOAT', 'Boat or Ship'), ('NONE', 'NONE')], max_length=500, null=True),
        ),
    ]
