# Generated by Django 3.2 on 2022-06-07 06:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_peopleeventlog_transportmodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleeventlog',
            name='transportmodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, choices=[('BICYCLE', 'Bicycle'), ('MOTORCYCLE', 'MotorCycle'), ('RICKSHAW', 'Rickshaw'), ('BUS', 'Bus'), ('TRAIN', 'Train'), ('FLITE', 'Flite'), ('BOAT', 'Boat or Ship'), ('NONE', 'NONE')], null=True, size=None),
        ),
    ]
