# Generated by Django 3.2 on 2022-06-30 12:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_alter_peopleeventlog_transportmodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleeventlog',
            name='otherlocation',
            field=models.CharField(default=None, max_length=50, verbose_name='Other Location'),
        ),
        migrations.AlterField(
            model_name='peopleeventlog',
            name='transportmodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('BIKE', 'Bike'), ('RICKSHAW', 'Rickshaw'), ('BUS', 'Bus'), ('TRAIN', 'Train'), ('PLANE', 'Plane'), ('BOAT', 'Boat or Ship'), ('NONE', 'NONE'), ('CAR', 'Car'), ('CAB', 'Cab')], default='NONE', max_length=50), default=list, size=None),
        ),
    ]
