# Generated by Django 3.2.18 on 2024-02-16 10:38

import apps.peoples.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0010_alter_subscription_terminateddate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='mdtz')),
                ('ctzoffset', models.IntegerField(default=-1, verbose_name='TimeZone')),
                ('name', models.CharField(max_length=100)),
                ('defaultprice', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=1000)),
                ('currency', models.CharField(max_length=100)),
                ('isactive', models.BooleanField(default=True)),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='features_cusers', to=settings.AUTH_USER_MODEL)),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='features_musers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'db_table': 'features',
                'ordering': ['mdtz'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='mdtz')),
                ('ctzoffset', models.IntegerField(default=-1, verbose_name='TimeZone')),
                ('discount', models.IntegerField(default=0)),
                ('fromdate', models.DateField()),
                ('uptodate', models.DateField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt', verbose_name='Client')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='discounts_cusers', to=settings.AUTH_USER_MODEL)),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='discounts_musers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'db_table': 'discounts',
                'ordering': ['mdtz'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='mdtz')),
                ('ctzoffset', models.IntegerField(default=-1, verbose_name='TimeZone')),
                ('newprice', models.IntegerField(default=0)),
                ('currency', models.CharField(max_length=100)),
                ('isactive', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt', verbose_name='Client')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='billing_cusers', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='clientbilling.features', verbose_name='Feature')),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='billing_musers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing',
                'verbose_name_plural': 'Billings',
                'db_table': 'billing',
                'ordering': ['mdtz'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='features',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_feature_name'),
        ),
        migrations.AddConstraint(
            model_name='discounts',
            constraint=models.UniqueConstraint(fields=('client', 'discount'), name='unique_client_discount'),
        ),
        migrations.AddConstraint(
            model_name='billing',
            constraint=models.UniqueConstraint(fields=('client', 'feature'), name='unique_client_feature'),
        ),
    ]
