# Generated by Django 3.2.18 on 2024-02-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientbilling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='currency',
        ),
    ]
