# Generated by Django 3.2.18 on 2024-02-23 10:51

import apps.peoples.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientbilling', '0002_remove_features_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='mdtz')),
                ('ctzoffset', models.IntegerField(default=-1, verbose_name='TimeZone')),
                ('comment', models.TextField(null=True, verbose_name='Comment')),
                ('approved', models.CharField(max_length=50, verbose_name='Approved')),
                ('approvedon', models.DateTimeField(verbose_name='Approved On')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approvals_cusers', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='clientbilling.features', verbose_name='Feature')),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approvals_musers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['mdtz'],
                'abstract': False,
            },
        ),
    ]
