# Generated by Django 4.2 on 2024-03-04 10:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientbilling', '0004_approvals_lastrequested_alter_approvals_approved_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Approvals',
            new_name='ApprovedFeature',
        ),
        migrations.AlterModelOptions(
            name='approvedfeature',
            options={'ordering': ['mdtz'], 'verbose_name': 'Approved Feature', 'verbose_name_plural': 'Approved Features'},
        ),
        migrations.AlterModelTable(
            name='approvedfeature',
            table='approvedfeatures',
        ),
    ]
