# Generated by Django 3.2.18 on 2023-05-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporthistory',
            name='cc_mails',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='reporthistory',
            name='email_body',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reporthistory',
            name='to_mails',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
