# Generated by Django 3.2.18 on 2023-12-13 02:00

import apps.peoples.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='mdtz')),
                ('ctzoffset', models.IntegerField(default=-1, verbose_name='TimeZone')),
                ('report_type', models.CharField(choices=[('', 'Select Report'), ('TaskSummary', 'Task Summary'), ('TourSummary', 'Tour Summary'), ('ListOfTasks', 'List of Tasks'), ('ListOfTours', 'List of Internal Tours'), ('PPMSummary', 'PPM Summary'), ('ListOfTickets', 'List of Tickets'), ('WorkOrderList', 'Work Order List'), ('SiteReport', 'Site Report'), ('PeopleQR', 'People-QR'), ('AssetQR', 'Asset-QR'), ('CheckpointQR', 'Checkpoint-QR'), ('AssetwiseTaskStatus', 'Assetwise Task Status'), ('DetailedTourSummary', 'Detailed Tour Summary')], max_length=50, verbose_name='Report Type')),
                ('report_name', models.CharField(max_length=55, verbose_name='Report Name')),
                ('cron', models.CharField(default='* * * * *', max_length=50, verbose_name='Scheduler')),
                ('report_sendtime', models.TimeField(verbose_name='Send Time')),
                ('cc', models.TextField(verbose_name='CC')),
                ('to_addr', models.TextField(verbose_name='To Address')),
                ('enable', models.BooleanField(default=True, verbose_name='Enable')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='schedulereport_cusers', to=settings.AUTH_USER_MODEL)),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='schedulereport_musers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['mdtz'],
                'abstract': False,
            },
        ),
    ]
