# Generated by Django 3.2.18 on 2023-05-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20230506_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporthistory',
            name='traceback',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
