# Generated by Django 3.2.18 on 2023-12-13 07:43

import apps.reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20231212_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulereport',
            name='report_params',
            field=models.JSONField(blank=True, default={'report_params': {}}, null=True),
        ),
        migrations.AlterField(
            model_name='reporthistory',
            name='datetime',
            field=models.DateTimeField(default=apps.reports.models.now),
        ),
    ]
