# Generated by Django 3.2.18 on 2023-12-14 02:32

import apps.reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20231213_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulereport',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='schedulereport',
            name='to_addr',
        ),
        migrations.AlterField(
            model_name='reporthistory',
            name='datetime',
            field=models.DateTimeField(default=apps.reports.models.now),
        ),
        migrations.AlterField(
            model_name='schedulereport',
            name='report_params',
            field=models.JSONField(blank=True, default=apps.reports.models.report_params_json, null=True),
        ),
    ]
