# Generated by Django 3.2.18 on 2023-12-14 02:33

import apps.reports.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20231213_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulereport',
            name='cc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=90, null=True), blank=True, null=True, size=None, verbose_name='Email-CC'),
        ),
        migrations.AddField(
            model_name='schedulereport',
            name='to_addr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=90, null=True), blank=True, null=True, size=None, verbose_name='Email=TO'),
        ),
        migrations.AlterField(
            model_name='reporthistory',
            name='datetime',
            field=models.DateTimeField(default=apps.reports.models.now),
        ),
    ]
