# Generated by Django 3.2.18 on 2023-12-14 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_auto_20231207_0056'),
        ('reports', '0006_auto_20231213_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulereport',
            name='bu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='schd_sites', to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='schedulereport',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='schd_clients', to='onboarding.bt'),
        ),
    ]
