# Generated by Django 3.2.18 on 2023-12-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20231213_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulereport',
            name='nextscheduledon',
            field=models.DateTimeField(null=True, verbose_name='Next Scheduled On'),
        ),
        migrations.AlterField(
            model_name='schedulereport',
            name='lastgeneratedon',
            field=models.DateTimeField(null=True, verbose_name='Last Generated On'),
        ),
    ]
