# Generated by Django 3.2.18 on 2023-12-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20231216_0520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulereport',
            old_name='lastgeneratedon',
            new_name='fromdatetime',
        ),
        migrations.RenameField(
            model_name='schedulereport',
            old_name='nextscheduledon',
            new_name='uptodatetime',
        ),
    ]
