# Generated by Django 3.2.18 on 2023-12-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20231216_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulereport',
            name='crontype',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cron Type'),
        ),
        migrations.AddField(
            model_name='schedulereport',
            name='lastgeneratedon',
            field=models.DateTimeField(null=True, verbose_name='Last Generated On'),
        ),
    ]
