# Generated by Django 3.2.18 on 2023-12-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20231216_0545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulereport',
            options={},
        ),
        migrations.AlterModelTable(
            name='schedulereport',
            table='schedule_report',
        ),
    ]
