# Generated by Django 3.2.18 on 2023-12-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20231217_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulereport',
            name='workingdays',
            field=models.CharField(blank=True, choices=[('5', 'Monday - Friday'), ('6', 'Monday - Saturday')], max_length=1, null=True, verbose_name='Working Days'),
        ),
    ]
