# Generated by Django 3.2.18 on 2023-12-18 11:57

import apps.reports.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_auto_20231207_0056'),
        ('reports', '0012_schedulereport_workingdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporthistory',
            name='cdtz',
            field=models.DateTimeField(default=apps.reports.models.now, verbose_name='cdtz'),
        ),
        migrations.AddField(
            model_name='reporthistory',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rh_clients', to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='reporthistory',
            name='has_data',
            field=models.BooleanField(default=True, verbose_name='Has Data in Report'),
        ),
        migrations.AddField(
            model_name='reporthistory',
            name='mdtz',
            field=models.DateTimeField(default=apps.reports.models.now, verbose_name='mdtz'),
        ),
    ]
