# Generated by Django 3.2.18 on 2023-12-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20231218_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporthistory',
            name='format',
        ),
        migrations.AlterField(
            model_name='reporthistory',
            name='traceback',
            field=models.TextField(null=True),
        ),
    ]
