# Generated by Django 3.2.18 on 2023-12-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20231219_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulereport',
            name='filename',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
