# Generated by Django 3.2.18 on 2023-12-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_schedulereport_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulereport',
            options={'ordering': ['mdtz']},
        ),
        migrations.AddConstraint(
            model_name='schedulereport',
            constraint=models.UniqueConstraint(fields=('cron', 'report_type', 'bu', 'report_params'), name='cron_report_type_report_params_uk'),
        ),
        migrations.AddConstraint(
            model_name='schedulereport',
            constraint=models.UniqueConstraint(fields=('cron', 'report_type', 'bu', 'workingdays', 'report_params'), name='cron_report_type_workindays_report_params_uk'),
        ),
    ]
