# Generated by Django 4.2 on 2024-07-29 12:23

import apps.peoples.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0018_alter_schedulereport_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='mdtz')),
                ('ctzoffset', models.IntegerField(default=-1, verbose_name='TimeZone')),
                ('additional_filter', models.CharField(max_length=255)),
                ('customer', models.CharField(default=None, max_length=255, null=True)),
                ('site', models.CharField(default=None, max_length=255, null=True)),
                ('number_of_period', models.CharField(max_length=255)),
                ('period_from', models.CharField(default=None, max_length=255, null=True)),
                ('period_to', models.CharField(default=None, max_length=255, null=True)),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL)),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'generatepdf',
                'ordering': ['mdtz'],
                'abstract': False,
            },
        ),
    ]
