# Generated by Django 4.2 on 2024-07-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_generatepdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatepdf',
            name='customer',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='generatepdf',
            name='period_from',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='generatepdf',
            name='period_to',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='generatepdf',
            name='site',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
