# Generated by Django 4.2 on 2024-07-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_alter_generatepdf_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatepdf',
            name='additional_filter',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SITE', 'Site')], max_length=60, verbose_name='Additional Filter'),
        ),
        migrations.AlterField(
            model_name='generatepdf',
            name='number_of_period',
            field=models.CharField(choices=[('ONE', 'One'), ('MULTIPLE', 'Multiple')], max_length=60, verbose_name='Number Of Period'),
        ),
    ]
