# Generated by Django 4.2 on 2024-08-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_alter_generatepdf_additional_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatepdf',
            name='company',
            field=models.CharField(choices=[('ONE', 'One'), ('MULTIPLE', 'Multiple')], default=None, max_length=60, null=True, verbose_name='Company'),
        ),
    ]
