# Generated by Django 4.2 on 2024-08-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_generatepdf_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatepdf',
            name='number_of_period',
        ),
        migrations.RemoveField(
            model_name='generatepdf',
            name='period_to',
        ),
        migrations.AlterField(
            model_name='generatepdf',
            name='company',
            field=models.CharField(choices=[('SPS', 'SPS'), ('SFS', 'SFS'), ('TARGET', 'TARGET')], max_length=60, null=True, verbose_name='Company'),
        ),
    ]
