# Generated by Django 4.2 on 2024-08-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_remove_generatepdf_number_of_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatepdf',
            name='document_type',
            field=models.CharField(choices=[('PF', 'PF'), ('ESIC', 'ESIC')], max_length=60, null=True, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='schedulereport',
            name='report_type',
            field=models.CharField(choices=[('', 'Select Report'), ('TASKSUMMARY', 'Task Summary'), ('TOURSUMMARY', 'Tour Summary'), ('LISTOFTASKS', 'List of Tasks'), ('LISTOFTOURS', 'List of Internal Tours'), ('PPMSUMMARY', 'PPM Summary'), ('LISTOFTICKETS', 'List of Tickets'), ('WORKORDERLIST', 'Work Order List'), ('SITEVISITREPORT', 'Site Visit Report'), ('SITEREPORT', 'Site Report'), ('PeopleQR', 'People-QR'), ('ASSETQR', 'Asset-QR'), ('CHECKPOINTQR', 'Checkpoint-QR'), ('ASSETWISETASKSTATUS', 'Assetwise Task Status'), ('DetailedTourSummary', 'Detailed Tour Summary'), ('STATICDETAILEDTOURSUMMARY', 'Static Detailed Tour Summary'), ('DYNAMICDETAILEDTOURSUMMARY', 'Dynamic Detailed Tour Summary'), ('DYNAMICTOURDETAILS', 'Dynamic Tour Details'), ('STATICTOURDETAILS', 'Static Tour Details'), ('RP_SITEVISITREPORT', 'RP Site Visit Report'), ('LOGSHEET', 'Log Sheet'), ('PEOPLEATTENDANCESUMMARY', 'People Attendance Summary')], max_length=50, verbose_name='Report Type'),
        ),
    ]
