# Generated by Django 3.2.18 on 2024-08-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_remove_generatepdf_number_of_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatepdf',
            name='document_type',
            field=models.CharField(choices=[('PF', 'PF'), ('ESIC', 'ESIC')], max_length=60, null=True, verbose_name='Document Type'),
        ),
    ]
