# Generated by Django 4.2 on 2025-02-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_generatepdf_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatepdf',
            name='document_type',
            field=models.CharField(choices=[('PF', 'PF'), ('ESIC', 'ESIC'), ('PAYROLL', 'PAYROLL')], max_length=60, null=True, verbose_name='Document Type'),
        ),
    ]
