# Generated by Django 4.2 on 2025-04-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_alter_generatepdf_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatepdf',
            name='type_of_form',
            field=models.CharField(choices=[('NORMAL FORM', 'NORMAL FORM'), ('FORM 16', 'FORM 16')], max_length=60, null=True, verbose_name='Type Of Form'),
        ),
    ]
