# Generated by Django 3.2.14 on 2023-02-09 10:25

import apps.reminder.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['mdtz'], 'verbose_name': 'Reminder', 'verbose_name_plural': 'Reminders'},
        ),
        migrations.AlterModelManagers(
            name='reminder',
            managers=[
                ('objects', apps.reminder.managers.ReminderManager()),
            ],
        ),
        migrations.AlterModelTable(
            name='reminder',
            table='reminder',
        ),
    ]
