# Generated by Django 3.2.18 on 2023-06-25 13:03

import apps.peoples.models
import apps.work_order_management.managers
import apps.work_order_management.models
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('onboarding', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='mdtz')),
                ('ctzoffset', models.IntegerField(default=-1, verbose_name='TimeZone')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, unique=True)),
                ('code', models.CharField(max_length=50, null=True, verbose_name='Code')),
                ('name', models.CharField(max_length=55, null=True, verbose_name='Name')),
                ('address', models.TextField(blank=True, max_length=500, null=True, verbose_name='Address')),
                ('gpslocation', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326, verbose_name='GPS Location')),
                ('enable', models.BooleanField(default=True, verbose_name='Enable')),
                ('mobno', models.CharField(max_length=15, verbose_name='Mob No')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('show_to_all_sites', models.BooleanField(default=False, verbose_name='Applicable to all sites')),
                ('bu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='vendor_bus', to='onboarding.bt', verbose_name='Site')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='vendor_clients', to='onboarding.bt', verbose_name='Client')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='vendor_cusers', to=settings.AUTH_USER_MODEL)),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='vendor_musers', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.typeassist', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'vendor company',
                'db_table': 'vendor',
                'ordering': ['mdtz'],
                'abstract': False,
            },
            managers=[
                ('objects', apps.work_order_management.managers.VendorManager()),
            ],
        ),
        migrations.CreateModel(
            name='Wom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='mdtz')),
                ('ctzoffset', models.IntegerField(default=-1, verbose_name='TimeZone')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, unique=True)),
                ('description', models.CharField(max_length=200, verbose_name='Job Description')),
                ('plandatetime', models.DateTimeField(null=True, verbose_name='Plan date time')),
                ('expirydatetime', models.DateTimeField(null=True, verbose_name='Expiry date time')),
                ('starttime', models.DateTimeField(null=True, verbose_name='Start time')),
                ('endtime', models.DateTimeField(null=True, verbose_name='Start time')),
                ('gpslocation', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326, verbose_name='GPS Location')),
                ('workstatus', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('RE_ASSIGNED', 'Re-Assigned'), ('COMPLETED', 'Completed'), ('INPROGRESS', 'Inprogress'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='ASSIGNED', max_length=60, null=True, verbose_name='Job Status')),
                ('seqno', models.SmallIntegerField(null=True, verbose_name='Serial No.')),
                ('approvers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=70), blank=True, null=True, size=None, verbose_name='Approvers')),
                ('workpermit', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='NOT_REQUIRED', max_length=35, verbose_name='Work Permit')),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('LOW', 'Low'), ('MEDIUM', 'Medium')], max_length=50, verbose_name='Priority')),
                ('performedby', models.CharField(max_length=55, verbose_name='Performed By')),
                ('alerts', models.BooleanField(default=False, null=True, verbose_name='Alerts')),
                ('ismailsent', models.BooleanField(default=False, verbose_name='Mail Sent')),
                ('isdenied', models.BooleanField(default=False, verbose_name='Denied')),
                ('geojson', models.JSONField(default=apps.work_order_management.models.geojson, null=True, verbose_name='Geo Json')),
                ('other_data', models.JSONField(default=apps.work_order_management.models.other_data, null=True, verbose_name='Other Data')),
                ('attachmentcount', models.IntegerField(default=0, verbose_name='Attachment Count')),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, null=True, size=None, verbose_name='Categories')),
                ('wo_history', models.JSONField(default=apps.work_order_management.models.wo_history_json, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='wo_assets', to='activity.asset', verbose_name='Asset')),
                ('bu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='wo_bus', to='onboarding.bt', verbose_name='Site')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='wo_clients', to='onboarding.bt', verbose_name='Client')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='wom_cusers', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.location', verbose_name='Location')),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='wom_musers', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='work_order_management.wom', verbose_name='Belongs to')),
                ('qset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.questionset', verbose_name='QuestionSet')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('ticketcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.typeassist', verbose_name='Notify Category')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='work_order_management.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'work order management',
                'db_table': 'wom',
                'ordering': ['mdtz'],
                'abstract': False,
            },
            managers=[
                ('objects', apps.work_order_management.managers.WorkOrderManager()),
            ],
        ),
        migrations.CreateModel(
            name='WomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='mdtz')),
                ('ctzoffset', models.IntegerField(default=-1, verbose_name='TimeZone')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('seqno', models.SmallIntegerField(verbose_name='SL #')),
                ('answertype', models.CharField(choices=[('CHECKBOX', 'Checkbox'), ('DATE', 'Date'), ('DROPDOWN', 'Dropdown'), ('EMAILID', 'Email Id'), ('MULTILINE', 'Multiline'), ('NUMERIC', 'Numeric'), ('SIGNATURE', 'Signature'), ('SINGLELINE', 'Single Line'), ('TIME', 'Time'), ('RATING', 'Rating'), ('BACKCAMERA', 'Back Camera'), ('FRONTCAMERA', 'Front Camera'), ('PEOPLELIST', 'People List'), ('SITELIST', 'Site List'), ('NONE', 'NONE')], max_length=50, null=True, verbose_name='Answer Type')),
                ('answer', models.CharField(default='', max_length=250, null=True, verbose_name='Answer')),
                ('isavpt', models.BooleanField(default=False, verbose_name='Attachement Required')),
                ('avpttype', models.CharField(blank=True, choices=[('BACKCAMPIC', 'Back Camera Pic'), ('FRONTCAMPIC', 'Front Camera Pic'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('NONE', 'NONE')], max_length=50, null=True, verbose_name='Attachment Type')),
                ('options', models.CharField(blank=True, max_length=200, null=True, verbose_name='Option')),
                ('min', models.DecimalField(decimal_places=4, max_digits=18, null=True, verbose_name='Min')),
                ('max', models.DecimalField(decimal_places=4, max_digits=18, null=True, verbose_name='Max')),
                ('alerton', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alert On')),
                ('ismandatory', models.BooleanField(default=True, verbose_name='Mandatory')),
                ('alerts', models.BooleanField(default=False, verbose_name='Alerts')),
                ('attachmentcount', models.IntegerField(default=0, verbose_name='Attachment count')),
                ('bu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='womdetails_bus', to='onboarding.bt', verbose_name='Site')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='womdetails_clients', to='onboarding.bt', verbose_name='Client')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='womdetails_cusers', to=settings.AUTH_USER_MODEL)),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='womdetails_musers', to=settings.AUTH_USER_MODEL)),
                ('qset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='qset_answers', to='activity.questionset')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='activity.question', verbose_name='')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('wom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='work_order_management.wom', verbose_name='Jobneed')),
            ],
            options={
                'verbose_name': 'Wom Details',
                'db_table': 'womdetails',
                'ordering': ['mdtz'],
                'abstract': False,
            },
            managers=[
                ('objects', apps.work_order_management.managers.WOMDetailsManager()),
            ],
        ),
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='mdtz')),
                ('ctzoffset', models.IntegerField(default=-1, verbose_name='TimeZone')),
                ('approverfor', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, null=True, size=None, verbose_name='Approvers')),
                ('sites', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, null=True, size=None, verbose_name='Sites')),
                ('forallsites', models.BooleanField(default=True, verbose_name='For all sites')),
                ('bu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt', verbose_name='')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approver_cusers', to=settings.AUTH_USER_MODEL)),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approver_musers', to=settings.AUTH_USER_MODEL)),
                ('people', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Approver')),
            ],
            options={
                'verbose_name': 'approver',
                'db_table': 'approver',
                'ordering': ['mdtz'],
                'abstract': False,
            },
            managers=[
                ('objects', apps.work_order_management.managers.ApproverManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='womdetails',
            constraint=models.UniqueConstraint(fields=('question', 'client', 'wom'), name='question_client'),
        ),
        migrations.AddConstraint(
            model_name='wom',
            constraint=models.UniqueConstraint(fields=('qset', 'client', 'id'), name='qset_client'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('code', 'client'), name='code_client'),
        ),
        migrations.AddConstraint(
            model_name='approver',
            constraint=models.UniqueConstraint(fields=('people', 'approverfor', 'sites'), name='people_approverfor_forallsites_sites_uk'),
        ),
    ]
