# Generated by Django 3.2.14 on 2023-03-16 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0008_auto_20230313_1437'),
        ('work_order_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approver',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approver_bus', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='approver',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approver_clients', to='onboarding.bt', verbose_name='Client'),
        ),
    ]
