# Generated by Django 3.2.18 on 2023-08-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='womdetails',
            name='question_client',
        ),
        migrations.RemoveField(
            model_name='womdetails',
            name='bu',
        ),
        migrations.RemoveField(
            model_name='womdetails',
            name='client',
        ),
        migrations.AddConstraint(
            model_name='womdetails',
            constraint=models.UniqueConstraint(fields=('question', 'wom'), name='question_client'),
        ),
    ]
