# Generated by Django 3.2.14 on 2023-03-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0002_auto_20230316_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approver',
            options={'ordering': ['mdtz'], 'verbose_name': 'Approver'},
        ),
        migrations.AlterModelTable(
            name='approver',
            table='approver',
        ),
    ]
