# Generated by Django 3.2.14 on 2023-03-18 01:52

import apps.work_order_management.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0003_auto_20230316_1751'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vendor',
            managers=[
                ('objects', apps.work_order_management.managers.VendorManager()),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Enable'),
        ),
    ]
