# Generated by Django 3.2.18 on 2023-10-26 12:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0003_approver_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wom',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=50), default=list, size=None),
        ),
    ]
