# Generated by Django 3.2.14 on 2023-03-18 02:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0004_auto_20230318_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='gpslocation',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326, verbose_name='GPS Location'),
        ),
    ]
