# Generated by Django 3.2.18 on 2023-12-07 07:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0004_alter_wom_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='gpslocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='GPS Location'),
        ),
        migrations.AlterField(
            model_name='wom',
            name='gpslocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='GPS Location'),
        ),
    ]
