# Generated by Django 3.2.14 on 2023-03-21 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0044_alter_questionset_type'),
        ('work_order_management', '0005_vendor_gpslocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wom',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.location', verbose_name='Location'),
        ),
    ]
