# Generated by Django 3.2.14 on 2023-03-21 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0006_alter_wom_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wom',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('LOW', 'Low'), ('MEDIUM', 'Medium')], max_length=50, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='wom',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='work_order_management.vendor', verbose_name='Vendor'),
        ),
    ]
