# Generated by Django 4.2 on 2024-06-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0006_alter_approver_cuser_alter_approver_muser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='womdetails',
            name='options',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Option'),
        ),
    ]
