# Generated by Django 3.2.14 on 2023-03-21 10:56

import apps.work_order_management.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0007_auto_20230321_0100'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='wom',
            managers=[
                ('objects', apps.work_order_management.managers.WorkOrderManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='wom',
            name='receivedonserver',
        ),
    ]
