# Generated by Django 4.2 on 2024-07-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0007_alter_womdetails_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='womdetails',
            name='answertype',
            field=models.CharField(choices=[('CHECKBOX', 'Checkbox'), ('DATE', 'Date'), ('DROPDOWN', 'Dropdown'), ('EMAILID', 'Email Id'), ('MULTILINE', 'Multiline'), ('NUMERIC', 'Numeric'), ('SIGNATURE', 'Signature'), ('SINGLELINE', 'Single Line'), ('TIME', 'Time'), ('RATING', 'Rating'), ('BACKCAMERA', 'Back Camera'), ('FRONTCAMERA', 'Front Camera'), ('PEOPLELIST', 'People List'), ('SITELIST', 'Site List'), ('NONE', 'NONE'), ('MULTISELECT', 'Multi Select')], max_length=50, null=True, verbose_name='Answer Type'),
        ),
    ]
