# Generated by Django 4.2 on 2024-07-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0008_alter_womdetails_answertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='wom',
            name='identifier',
            field=models.CharField(blank=True, choices=[('WO', 'Work Order'), ('WP', 'Work Permit'), ('SLA', 'Service Level Agreement')], max_length=50, null=True, verbose_name='Identifier'),
        ),
    ]
