# Generated by Django 3.2.14 on 2023-03-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0008_auto_20230321_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wom',
            name='gracetime',
            field=models.IntegerField(blank=True, null=True, verbose_name='Grace time'),
        ),
    ]
