# Generated by Django 3.2.14 on 2023-03-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0009_alter_wom_gracetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wom',
            name='workpermit',
            field=models.CharField(choices=[('NOTNEED', 'Not Need'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PARTIALLY_APPROVED', 'Partially Approved')], default='NOTNEED', max_length=35, verbose_name='Work Permit'),
        ),
        migrations.AlterField(
            model_name='wom',
            name='workstatus',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('INPROGRESS', 'Inprogress'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=60, null=True, verbose_name='Job Status'),
        ),
    ]
