# Generated by Django 3.2.14 on 2023-03-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0010_auto_20230321_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='wom',
            name='isdenied',
            field=models.BooleanField(default=False, verbose_name='Is Denied'),
        ),
        migrations.AlterField(
            model_name='wom',
            name='workpermit',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PARTIALLY_APPROVED', 'Partially Approved')], default='NOT_REQUIRED', max_length=35, verbose_name='Work Permit'),
        ),
    ]
