# Generated by Django 4.2 on 2024-08-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0010_vendor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='approver',
            name='identifier',
            field=models.CharField(blank=True, choices=[('APPROVER', 'Approver'), ('VERIFIER', 'Verifier')], max_length=250, null=True, verbose_name='Approver/Verifier'),
        ),
    ]
