# Generated by Django 4.2 on 2024-08-29 13:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0011_approver_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approver',
            name='approverfor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, verbose_name='Approver/Verifier For'), blank=True, null=True, size=None),
        ),
    ]
