# Generated by Django 3.2.14 on 2023-03-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0011_auto_20230321_0743'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wom',
            name='qset_client',
        ),
        migrations.AddConstraint(
            model_name='wom',
            constraint=models.UniqueConstraint(fields=('qset', 'client', 'id'), name='qset_client'),
        ),
    ]
