# Generated by Django 4.2 on 2024-08-29 13:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0012_alter_approver_approverfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='wom',
            name='verifiers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None, verbose_name='Verifiers'),
        ),
        migrations.AlterField(
            model_name='wom',
            name='approvers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None, verbose_name='Approvers'),
        ),
    ]
