# Generated by Django 3.2.14 on 2023-03-22 12:39

import apps.work_order_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0012_auto_20230321_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='wom',
            name='other_data',
            field=models.JSONField(default=apps.work_order_management.models.other_data, null=True, verbose_name='Other Data'),
        ),
        migrations.AlterField(
            model_name='wom',
            name='geojson',
            field=models.JSONField(default=apps.work_order_management.models.geojson, null=True, verbose_name='Geo Json'),
        ),
    ]
