# Generated by Django 4.2 on 2024-08-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0013_wom_verifiers_alter_wom_approvers'),
    ]

    operations = [
        migrations.AddField(
            model_name='wom',
            name='verifiers_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='NOT_REQUIRED', verbose_name='Verifier Status'),
        ),
    ]
