# Generated by Django 3.2.14 on 2023-03-24 06:36

import apps.work_order_management.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0013_auto_20230322_0739'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='womdetails',
            managers=[
                ('objects', apps.work_order_management.managers.WOMDetailsManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='wom',
            name='gracetime',
        ),
        migrations.AddField(
            model_name='wom',
            name='seqno',
            field=models.SmallIntegerField(null=True, verbose_name='Serial No.'),
        ),
    ]
