# Generated by Django 4.2 on 2024-08-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0014_wom_verifiers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wom',
            name='verifiers_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', verbose_name='Verifier Status'),
        ),
    ]
