# Generated by Django 3.2.14 on 2023-03-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0014_auto_20230324_0136'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='womdetails',
            name='question_client',
        ),
        migrations.AddConstraint(
            model_name='womdetails',
            constraint=models.UniqueConstraint(fields=('question', 'client', 'wom'), name='question_client'),
        ),
    ]
