# Generated by Django 3.2.14 on 2023-04-01 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0009_bt_uuid'),
        ('work_order_management', '0015_auto_20230326_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.typeassist', verbose_name='Type'),
        ),
    ]
