# Generated by Django 4.2 on 2024-08-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0015_alter_wom_verifiers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wom',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
    ]
