# Generated by Django 3.2.14 on 2023-04-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0016_vendor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='show_to_all_sites',
            field=models.BooleanField(default=False, verbose_name='Applicable to all sites'),
        ),
    ]
