# Generated by Django 4.2 on 2024-09-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0016_wom_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wom',
            name='remarks',
            field=models.JSONField(blank=True, null=True, verbose_name='Remarks'),
        ),
    ]
