# Generated by Django 4.2 on 2024-09-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0017_alter_wom_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='wom',
            name='verifiers_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=50, verbose_name='Verifier Status'),
        ),
    ]
