# Generated by Django 3.2.18 on 2023-05-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0017_vendor_show_to_all_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wom',
            name='isdenied',
            field=models.BooleanField(default=False, verbose_name='Denied'),
        ),
        migrations.AlterField(
            model_name='wom',
            name='ismailsent',
            field=models.BooleanField(default=False, verbose_name='Mail Sent'),
        ),
        migrations.AlterField(
            model_name='womdetails',
            name='isavpt',
            field=models.BooleanField(default=False, verbose_name='Attachement Required'),
        ),
        migrations.AlterField(
            model_name='womdetails',
            name='ismandatory',
            field=models.BooleanField(default=True, verbose_name='Mandatory'),
        ),
    ]
