# Generated by Django 4.2 on 2025-01-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0018_alter_vendor_name_alter_wom_verifiers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wom',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('LOW', 'Low'), ('MEDIUM', 'Medium')], default='LOW', max_length=50, verbose_name='Priority'),
        ),
    ]
