# Generated by Django 3.2.18 on 2023-05-15 10:30

import apps.work_order_management.models
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0019_alter_wom_workstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='wom',
            name='wo_history',
            field=models.JSONField(default=apps.work_order_management.models.wo_history_json, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
