# Generated by Django 3.2.18 on 2023-05-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0020_wom_wo_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wom',
            name='expirydatetime',
            field=models.DateTimeField(null=True, verbose_name='Expiry date time'),
        ),
        migrations.AlterField(
            model_name='wom',
            name='plandatetime',
            field=models.DateTimeField(null=True, verbose_name='Plan date time'),
        ),
    ]
