# Generated by Django 3.2.18 on 2023-05-17 11:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0021_auto_20230517_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='wom',
            name='approvers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=70), blank=True, null=True, size=None, verbose_name='Approvers'),
        ),
    ]
