# Generated by Django 3.2.18 on 2023-05-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0022_wom_approvers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wom',
            name='workpermit',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='NOT_REQUIRED', max_length=35, verbose_name='Work Permit'),
        ),
    ]
