# Generated by Django 3.2.18 on 2023-05-19 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0054_alter_asset_runningstatus'),
        ('work_order_management', '0023_alter_wom_workpermit'),
    ]

    operations = [
        migrations.AddField(
            model_name='womdetails',
            name='qset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='qset_answers', to='activity.questionset'),
        ),
    ]
