# Generated by Django 3.2.18 on 2023-05-23 05:59

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_order_management', '0024_womdetails_qset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approver',
            options={'ordering': ['mdtz'], 'verbose_name': 'approver'},
        ),
        migrations.RemoveField(
            model_name='approver',
            name='bu',
        ),
        migrations.RemoveField(
            model_name='approver',
            name='client',
        ),
        migrations.RemoveField(
            model_name='approver',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='approver',
            name='wom',
        ),
        migrations.AddField(
            model_name='approver',
            name='approverfor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, null=True, size=None, verbose_name='Approvers'),
        ),
        migrations.AddField(
            model_name='approver',
            name='forallsites',
            field=models.BooleanField(default=True, verbose_name='For all sites'),
        ),
        migrations.AddField(
            model_name='approver',
            name='sites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, null=True, size=None, verbose_name='Sites'),
        ),
        migrations.AlterField(
            model_name='approver',
            name='people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Approver'),
        ),
        migrations.AddConstraint(
            model_name='approver',
            constraint=models.UniqueConstraint(fields=('people', 'approverfor', 'sites'), name='people_approverfor_forallsites_sites_uk'),
        ),
    ]
