# Generated by Django 3.2.18 on 2023-05-23 07:04

import apps.work_order_management.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0010_auto_20230512_0128'),
        ('work_order_management', '0025_auto_20230523_0059'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='approver',
            managers=[
                ('objects', apps.work_order_management.managers.ApproverManager()),
            ],
        ),
        migrations.AddField(
            model_name='approver',
            name='bu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt', verbose_name=''),
        ),
    ]
