# Generated by Django 3.2.18 on 2023-05-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order_management', '0026_auto_20230523_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wom',
            name='workstatus',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('RE_ASSIGNED', 'Re-Assigned'), ('COMPLETED', 'Completed'), ('INPROGRESS', 'Inprogress'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='ASSIGNED', max_length=60, null=True, verbose_name='Job Status'),
        ),
    ]
